/* eslint-disable */
// Generated by scripts/generate_operator_product_contracts.py. Do not edit manually.

export type CaptchaProvider = "disabled" | "hcaptcha" | "recaptcha" | "turnstile";

export interface AuthConfig {
  auth_mode: string;
  signup_enabled: boolean;
  password_auth_enabled: boolean;
  captcha: {
    provider: CaptchaProvider;
    site_key: string;
    configured: boolean;
    dev_bypass_enabled: boolean;
  };
  oauth: {
    google: { configured: boolean };
    github: { configured: boolean };
  };
  invite: {
    required: boolean;
    configured: boolean;
    allowlist_enabled: boolean;
  };
}

export interface UserProfile {
  id: string;
  email: string;
  display_name: string;
}

export interface TeamProfile {
  id: string;
  name: string;
  display_name: string;
  slug: string;
  role: string;
  roles: string[];
  members: { email: string; role: string; status: string }[];
}

export interface SessionPayload {
  user: UserProfile;
  teams: TeamProfile[];
  active_team: TeamProfile | null;
  settings: Record<string, string>;
}

export interface DashboardPayload {
  scope: { kind: "solo" | "team"; team: TeamProfile | null };
  session: SessionPayload;
  settings: Record<string, string>;
  settings_schema: Record<string, { values: string[]; default: string; description: string }>;
  mesh: Record<string, any>;
  authority_boundary: string;
}

export interface SettingsUpdateResponse {
  settings: Record<string, string>;
  settings_schema: Record<string, { values: string[]; default: string; description: string }>;
  audit: {
    recorded: boolean;
    state_slice: string;
    scope: string;
    fields: string[];
  };
}

export interface LogoutResponse {
  status: string;
}
