#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Any


def main() -> int:
    parser = argparse.ArgumentParser(description="Normalize release SBOM and vulnerability scan artifacts for provenance.")
    parser.add_argument("--sbom-input", required=True, help="CycloneDX SBOM JSON generated by the release image scan.")
    parser.add_argument("--scan-input", action="append", default=[], help="Raw vulnerability scan JSON. Repeatable.")
    parser.add_argument("--scanner", default="release-assurance", help="Scanner identity to write into the normalized scan artifact.")
    parser.add_argument("--output-dir", required=True, help="Directory for normalized release artifacts.")
    parser.add_argument("--image-digest", default="", help="Release image digest these artifacts describe.")
    parser.add_argument("--require-scan", action="store_true", help="Fail when no vulnerability scan input is provided.")
    parser.add_argument("--fail-on-blocking", action="store_true", help="Fail when high or critical findings are present.")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    sbom_output = output_dir / "sbom.cdx.json"
    scan_output = output_dir / "vulnerability-scan.json"

    sbom = _load_json(Path(args.sbom_input))
    _validate_cyclonedx_sbom(sbom, Path(args.sbom_input))
    if args.image_digest:
        _validate_image_digest(args.image_digest)
        _attach_sbom_image_digest(sbom, args.image_digest)
    sbom_output.write_text(json.dumps(sbom, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    if args.require_scan and not args.scan_input:
        raise SystemExit("--require-scan needs at least one --scan-input")

    findings: list[dict[str, Any]] = []
    source_files: list[str] = []
    for raw_input in args.scan_input:
        path = Path(raw_input)
        payload = _load_json(path)
        source_files.append(str(path))
        findings.extend(_extract_findings(payload, source=str(path)))

    normalized_scan = {
        "schema_version": "mesh.normalized_vulnerability_scan.v1",
        "generated_at": _timestamp(),
        "scanner": args.scanner,
        "image_digest": args.image_digest or None,
        "source_files": source_files,
        "findings": findings,
        "blocking_finding_count": sum(1 for finding in findings if _severity_rank(str(finding.get("severity") or "")) >= 3),
    }
    scan_output.write_text(json.dumps(normalized_scan, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    if args.fail_on_blocking and normalized_scan["blocking_finding_count"]:
        raise SystemExit(f"blocking vulnerability findings present: {normalized_scan['blocking_finding_count']}")

    print(
        json.dumps(
            {
                "schema_version": "mesh.release_assurance_artifact_normalization.v1",
                "status": "complete",
                "sbom": str(sbom_output),
                "vulnerability_scan": str(scan_output),
                "finding_count": len(findings),
                "blocking_finding_count": normalized_scan["blocking_finding_count"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


def _load_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"failed to read JSON artifact {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise SystemExit(f"JSON artifact {path} must be an object")
    return payload


def _validate_cyclonedx_sbom(payload: dict[str, Any], path: Path) -> None:
    if payload.get("bomFormat") != "CycloneDX":
        raise SystemExit(f"SBOM {path} must use bomFormat CycloneDX")


def _validate_image_digest(value: str) -> None:
    if not _valid_digest(value):
        raise SystemExit("--image-digest must be sha256:<64 hex>")


def _attach_sbom_image_digest(payload: dict[str, Any], image_digest: str) -> None:
    metadata = payload.setdefault("metadata", {})
    if not isinstance(metadata, dict):
        metadata = {}
        payload["metadata"] = metadata
    properties = metadata.setdefault("properties", [])
    if not isinstance(properties, list):
        properties = []
        metadata["properties"] = properties
    properties[:] = [
        item
        for item in properties
        if not (isinstance(item, dict) and item.get("name") == "mesh:image_digest")
    ]
    properties.append({"name": "mesh:image_digest", "value": image_digest})


def _extract_findings(payload: dict[str, Any], *, source: str) -> list[dict[str, Any]]:
    if isinstance(payload.get("matches"), list):
        return _extract_grype_findings(payload, source=source)
    if isinstance(payload.get("vulnerabilities"), dict):
        return _extract_npm_audit_findings(payload, source=source)
    if isinstance(payload.get("results"), list):
        return _extract_osv_findings(payload, source=source)
    if isinstance(payload.get("findings"), list):
        return [_normalized_existing_finding(item, source=source) for item in payload["findings"] if isinstance(item, dict)]
    return []


def _extract_grype_findings(payload: dict[str, Any], *, source: str) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    for item in payload.get("matches", []):
        if not isinstance(item, dict):
            continue
        vulnerability = item.get("vulnerability") if isinstance(item.get("vulnerability"), dict) else {}
        artifact = item.get("artifact") if isinstance(item.get("artifact"), dict) else {}
        findings.append(
            _finding(
                vulnerability_id=str(vulnerability.get("id") or ""),
                severity=str(vulnerability.get("severity") or ""),
                package=str(artifact.get("name") or ""),
                version=str(artifact.get("version") or ""),
                source=source,
            )
        )
    return findings


def _extract_npm_audit_findings(payload: dict[str, Any], *, source: str) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    vulnerabilities = payload.get("vulnerabilities")
    if not isinstance(vulnerabilities, dict):
        return findings
    for package_name, item in vulnerabilities.items():
        if not isinstance(item, dict):
            continue
        finding_id = str(item.get("name") or package_name)
        via = item.get("via")
        if isinstance(via, list):
            advisory_ids = [
                str(advisory.get("source") or advisory.get("url") or advisory.get("title") or "")
                for advisory in via
                if isinstance(advisory, dict)
            ]
            finding_id = ",".join(item for item in advisory_ids if item) or finding_id
        findings.append(
            _finding(
                vulnerability_id=finding_id,
                severity=str(item.get("severity") or ""),
                package=str(package_name),
                version="",
                source=source,
            )
        )
    return findings


def _extract_osv_findings(payload: dict[str, Any], *, source: str) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    for result in payload.get("results", []):
        if not isinstance(result, dict):
            continue
        packages = result.get("packages") if isinstance(result.get("packages"), list) else [result]
        for package_record in packages:
            if not isinstance(package_record, dict):
                continue
            package = package_record.get("package") if isinstance(package_record.get("package"), dict) else {}
            vulnerabilities = package_record.get("vulnerabilities") if isinstance(package_record.get("vulnerabilities"), list) else []
            for vulnerability in vulnerabilities:
                if not isinstance(vulnerability, dict):
                    continue
                findings.append(
                    _finding(
                        vulnerability_id=str(vulnerability.get("id") or ""),
                        severity=_osv_severity(vulnerability),
                        package=str(package.get("name") or package_record.get("name") or ""),
                        version=str(package.get("version") or package_record.get("version") or ""),
                        source=source,
                    )
                )
    return findings


def _normalized_existing_finding(item: dict[str, Any], *, source: str) -> dict[str, Any]:
    return _finding(
        vulnerability_id=str(item.get("id") or item.get("vulnerability_id") or ""),
        severity=str(item.get("severity") or ""),
        package=str(item.get("package") or ""),
        version=str(item.get("version") or ""),
        source=source,
    )


def _finding(*, vulnerability_id: str, severity: str, package: str, version: str, source: str) -> dict[str, Any]:
    return {
        "id": vulnerability_id or "unknown",
        "severity": severity.strip().lower() or "unknown",
        "package": package or None,
        "version": version or None,
        "source": source,
    }


def _osv_severity(vulnerability: dict[str, Any]) -> str:
    database_specific = vulnerability.get("database_specific")
    if isinstance(database_specific, dict) and isinstance(database_specific.get("severity"), str):
        return database_specific["severity"]
    severities = vulnerability.get("severity")
    if isinstance(severities, list):
        for item in severities:
            if isinstance(item, dict) and isinstance(item.get("score"), str):
                return item["score"]
    return ""


def _severity_rank(severity: str) -> int:
    normalized = severity.strip().lower()
    if normalized in {"critical", "crit"}:
        return 4
    if normalized == "high":
        return 3
    if normalized == "medium":
        return 2
    if normalized == "low":
        return 1
    return 0


def _valid_digest(value: str) -> bool:
    if not value.startswith("sha256:"):
        return False
    tail = value[len("sha256:") :]
    return len(tail) == 64 and all(char in "0123456789abcdefABCDEF" for char in tail)


def _timestamp() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


if __name__ == "__main__":
    raise SystemExit(main())
