#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]

IMAGE_DEFAULTS = {
    "docker-compose.prod.yml": ("${MESH_IMAGE:-orbital-mesh:",),
    "docker-compose.stack.yml": (
        "${HERMES_RUNTIME_IMAGE:-orbital-mesh-hermes:",
        "${MESH_STACK_IMAGE:-orbital-mesh-stack:",
        "${MESH_LATENTMAS_IMAGE:-orbital-mesh-latentmas:",
    ),
}

REQUIRED_DOCS = (
    "docs/production-hardening-records.md",
    "docs/evaluation-kits.md",
    "docs/community-governance.md",
    "docs/design-partner-packet.md",
    "docs/postgres-restart-proof.md",
    "docs/release-provenance.md",
    "docs/authenticated-ingress.md",
    "docs/reference-architectures.md",
    "docs/deployment-compatibility.md",
    "docs/agentic-operator-core-import-plan.md",
    "docs/pilot-slo-error-budget.md",
    "docs/post-training/runtime.md",
    "docs/security-audit-readiness.md",
    "docs/darkharness-operator-runbook.md",
)

REQUIRED_TESTS = (
    "tests/test_darkharness_packet.py",
    "tests/test_darkharness_policy.py",
    "tests/test_darkharness_export_path.py",
    "tests/test_darkharness_live_verifier.py",
    "tests/test_repo_patch_service_image_bundle.py",
    "tests/test_repo_patch_service_image_release_workflow.py",
    "tests/test_syft_binary_identity.py",
)

REQUIRED_SCRIPTS = (
    "scripts/compose_stack_smoke.sh",
    "scripts/prod_smoke.sh",
    "scripts/e2e_ui_operator.sh",
    "scripts/verify_postgres_restart_proof.py",
    "scripts/collect_release_image_metadata.py",
    "scripts/generate_release_image_handoff.py",
    "scripts/verify_release_image_handoff.py",
    "scripts/verify_e2e_claim.py",
    "scripts/generate_release_provenance.py",
    "scripts/generate_ci_attestation.py",
    "scripts/generate_release_assurance_rehearsal_inputs.py",
    "scripts/generate_release_image_assurance.py",
    "scripts/normalize_release_assurance_artifacts.py",
    "scripts/normalize_syft_binary_identity.py",
    "scripts/verify_release_artifact_bundle.py",
    "scripts/verify_release_runtime_binding.py",
    "scripts/generate_repo_patch_service_image_bundle.py",
    "scripts/verify_repo_patch_service_image_bundle.py",
    "scripts/verify_pilot_clearance.py",
    "scripts/verify_authenticated_ingress.py",
    "scripts/verify_authenticated_ingress_deployment.py",
    "scripts/verify_failure_mode_library.py",
    "scripts/verify_threat_model_register.py",
    "scripts/verify_data_classification_policy.py",
    "scripts/verify_agentic_operator_source_provenance.py",
    "scripts/verify_deployment_compatibility.py",
    "scripts/verify_ecs_fargate_promotion.py",
    "scripts/generate_evaluation_kit_packet.py",
    "scripts/verify_evaluation_kit_packet.py",
    "scripts/verify_benchmark_run_artifacts.py",
    "scripts/verify_mesh_brain_artifact_registry.py",
    "scripts/purge_run_exports.py",
    "scripts/verify_run_export_retrieval.py",
    "scripts/verify_run_export_upload.py",
    "scripts/run_backup_restore_rehearsal.py",
    "scripts/verify_backup_restore_rehearsal.py",
    "scripts/run_load_concurrency_rehearsal.py",
    "scripts/verify_load_concurrency_rehearsal.py",
    "scripts/capture_production_live_proof_bundle.py",
    "scripts/generate_production_live_proof_bundle.py",
    "scripts/verify_production_target_proof.py",
    "scripts/generate_orchestration_topology_drill.py",
    "scripts/verify_orchestration_topology_drill.py",
    "scripts/verify_watch_mode_proof.py",
    "scripts/verify_incident_coverage_proof.py",
    "scripts/verify_provider_adapter_proof.py",
    "scripts/generate_migration_rehearsal.py",
    "scripts/run_postgres_migration_rehearsal.py",
    "scripts/verify_migration_rehearsal.py",
    "scripts/verify_on_call_drill.py",
    "scripts/verify_pilot_signoff.py",
    "scripts/verify_design_partner_packet.py",
    "scripts/verify_procurement_security_package.py",
    "scripts/verify_public_proof_package.py",
    "scripts/verify_security_audit_readiness.py",
    "scripts/verify_darkharness_live_packet.py",
    "scripts/verify_audit_sink_contract.py",
    "scripts/verify_audit_sink_certification.py",
    "scripts/verify_credential_rotation.py",
)

REQUIRED_CONFIGS = (
    "config/release-vulnerability-exceptions.json",
)

REQUIRED_API_MARKERS = (
    "/api/readiness",
    "/api/kill-switch",
    "/api/pilot/go-no-go",
    "/api/darkharness/pilot-packet",
    "/api/policy/simulate",
    "/api/policy/lifecycle",
    "/api/connectors/certification",
    "/api/deployment/compatibility",
    "/api/failure-modes",
    "/api/approvals",
    "/api/watchers/ownership",
    "/api/runs/{run_id}/timeline-proof",
)

REQUIRED_MARKERS = {
    "docker-compose.prod.yml": (
        '${MESH_PUBLISH_HOST:-127.0.0.1}:${MESH_PUBLISH_PORT:-8787}:8787',
        'MESH_READINESS_PROFILE: "${MESH_READINESS_PROFILE:-pilot}"',
        'MESH_STATE_BACKEND: "${MESH_STATE_BACKEND:-postgres}"',
        'MESH_DATABASE_URL: "${MESH_DATABASE_URL:?set Postgres database URL for production state}"',
        'MESH_OPERATOR_IDENTITY_REQUIRED: "${MESH_OPERATOR_IDENTITY_REQUIRED:-1}"',
        'MESH_AUTHENTICATED_INGRESS_PROOF_PATH: "${MESH_AUTHENTICATED_INGRESS_PROOF_PATH:?set authenticated ingress deployment proof path}"',
        'MESH_DESIGN_PARTNER_PACKET_PATH: "${MESH_DESIGN_PARTNER_PACKET_PATH:?set design partner pilot packet path}"',
        'MESH_FORCE_APPROVAL_GATE: "${MESH_FORCE_APPROVAL_GATE:-1}"',
        'MESH_TENANT_ACTIVE_RUN_QUOTA: "${MESH_TENANT_ACTIVE_RUN_QUOTA:-4}"',
        'MESH_LIVE_FEEDBACK_REQUIRED: "${MESH_LIVE_FEEDBACK_REQUIRED:-1}"',
        'MESH_FEEDBACK_PROMETHEUS_ENABLED: "${MESH_FEEDBACK_PROMETHEUS_ENABLED:-1}"',
        'MESH_PROMETHEUS_URL: "${MESH_PROMETHEUS_URL:?set production Prometheus URL for feedback and telemetry}"',
        'MESH_BRAIN_ARTIFACT_URI_PREFIX: "${MESH_BRAIN_ARTIFACT_URI_PREFIX:?set durable object-storage URI prefix for Mesh Brain artifacts}"',
        'MESH_BRAIN_ARTIFACT_REGISTRY_PATH: "${MESH_BRAIN_ARTIFACT_REGISTRY_PATH:?set Mesh Brain artifact registry export path}"',
        'MESH_BRAIN_ARTIFACT_UPLOAD_PROOF_PATH: "${MESH_BRAIN_ARTIFACT_UPLOAD_PROOF_PATH:?set Mesh Brain artifact upload proof manifest path}"',
        'MESH_BRAIN_SERVING_BASE_URL: "${MESH_BRAIN_SERVING_BASE_URL:?set OpenAI-compatible Mesh Brain serving backend URL}"',
        'MESH_BRAIN_SERVING_MODEL: "${MESH_BRAIN_SERVING_MODEL:?set Mesh Brain serving model name}"',
        'MESH_RUN_EXPORT_RETENTION_DAYS: "${MESH_RUN_EXPORT_RETENTION_DAYS:-30}"',
        'MESH_RUN_EXPORT_RETENTION_REVIEWED: "${MESH_RUN_EXPORT_RETENTION_REVIEWED:?set MESH_RUN_EXPORT_RETENTION_REVIEWED=1 after reviewing pilot retention policy}"',
        'MESH_OWNERSHIP_REGISTRY_PATH: "${MESH_OWNERSHIP_REGISTRY_PATH:-/app/config/ownership.registry.json}"',
        'MESH_CONNECTOR_CERTIFICATION_REGISTRY_PATH: "${MESH_CONNECTOR_CERTIFICATION_REGISTRY_PATH:-/app/config/connector-certification.registry.json}"',
        'MESH_POLICY_LIFECYCLE_MANIFEST_PATH: "${MESH_POLICY_LIFECYCLE_MANIFEST_PATH:-/app/config/policy-lifecycle.manifest.json}"',
        'MESH_ORCHESTRATION_TOPOLOGY_PROFILE_PATH: "${MESH_ORCHESTRATION_TOPOLOGY_PROFILE_PATH:-/app/config/orchestration-topology.profile.json}"',
        'MESH_ORCHESTRATION_TOPOLOGY_DRILL_PATH: "${MESH_ORCHESTRATION_TOPOLOGY_DRILL_PATH:-}"',
        'MESH_FAILURE_MODE_LIBRARY_PATH: "${MESH_FAILURE_MODE_LIBRARY_PATH:-/app/config/failure-mode.library.json}"',
        'MESH_THREAT_MODEL_REGISTER_PATH: "${MESH_THREAT_MODEL_REGISTER_PATH:-/app/config/threat-model.register.json}"',
        'MESH_DATA_CLASSIFICATION_POLICY_PATH: "${MESH_DATA_CLASSIFICATION_POLICY_PATH:-/app/config/data-classification.policy.json}"',
        'MESH_AGENTIC_OPERATOR_SOURCE_PROVENANCE_PATH: "${MESH_AGENTIC_OPERATOR_SOURCE_PROVENANCE_PATH:-/app/config/agentic-operator-source.provenance.json}"',
        'MESH_DEPLOYMENT_COMPATIBILITY_REGISTRY_PATH: "${MESH_DEPLOYMENT_COMPATIBILITY_REGISTRY_PATH:-/app/config/deployment-compatibility.registry.json}"',
        'MESH_RELEASE_PROVENANCE_PATH: "${MESH_RELEASE_PROVENANCE_PATH:?set complete release provenance packet path}"',
        'MESH_AUDIT_SINK_PROOF_PATH: "${MESH_AUDIT_SINK_PROOF_PATH:-}"',
        'MESH_AUDIT_SINK_CERTIFICATION_PATH: "${MESH_AUDIT_SINK_CERTIFICATION_PATH:-}"',
        'MESH_ON_CALL_DRILL_PATH: "${MESH_ON_CALL_DRILL_PATH:?set production on-call drill proof path}"',
        'MESH_POLICY_SIGNING_KEY: "${MESH_POLICY_SIGNING_KEY:-}"',
        'MESH_POLICY_SIGNING_KEY_PATH: "${MESH_POLICY_SIGNING_KEY_PATH:-}"',
        'MESH_BUILD_COMMIT: "${MESH_BUILD_COMMIT:?set release git commit from release provenance packet}"',
        'MESH_BUILD_IMAGE_DIGEST: "${MESH_BUILD_IMAGE_DIGEST:?set release image digest from release provenance packet}"',
    ),
    "docker-compose.stack.yml": (
        'MESH_STATE_BACKEND: "${MESH_STATE_BACKEND:-postgres}"',
        'MESH_DEFAULT_STEERING_MODE: "${MESH_DEFAULT_STEERING_MODE:-approval_gate}"',
        'MESH_OPERATOR_IDENTITY_REQUIRED: "${MESH_OPERATOR_IDENTITY_REQUIRED:-1}"',
        'MESH_AUTHENTICATED_INGRESS_PROOF_PATH: "${MESH_AUTHENTICATED_INGRESS_PROOF_PATH:-}"',
        'MESH_TENANT_ACTIVE_RUN_QUOTA: "${MESH_TENANT_ACTIVE_RUN_QUOTA:-4}"',
        'MESH_OWNERSHIP_REGISTRY_PATH: "${MESH_OWNERSHIP_REGISTRY_PATH:-/app/config/ownership.registry.json}"',
        'MESH_CONNECTOR_CERTIFICATION_REGISTRY_PATH: "${MESH_CONNECTOR_CERTIFICATION_REGISTRY_PATH:-/app/config/connector-certification.registry.json}"',
        'MESH_POLICY_LIFECYCLE_MANIFEST_PATH: "${MESH_POLICY_LIFECYCLE_MANIFEST_PATH:-/app/config/policy-lifecycle.manifest.json}"',
        'MESH_ORCHESTRATION_TOPOLOGY_PROFILE_PATH: "${MESH_ORCHESTRATION_TOPOLOGY_PROFILE_PATH:-/app/config/orchestration-topology.profile.json}"',
        'MESH_ORCHESTRATION_TOPOLOGY_DRILL_PATH: "${MESH_ORCHESTRATION_TOPOLOGY_DRILL_PATH:-}"',
        'MESH_FAILURE_MODE_LIBRARY_PATH: "${MESH_FAILURE_MODE_LIBRARY_PATH:-/app/config/failure-mode.library.json}"',
        'MESH_THREAT_MODEL_REGISTER_PATH: "${MESH_THREAT_MODEL_REGISTER_PATH:-/app/config/threat-model.register.json}"',
        'MESH_DATA_CLASSIFICATION_POLICY_PATH: "${MESH_DATA_CLASSIFICATION_POLICY_PATH:-/app/config/data-classification.policy.json}"',
        'MESH_AGENTIC_OPERATOR_SOURCE_PROVENANCE_PATH: "${MESH_AGENTIC_OPERATOR_SOURCE_PROVENANCE_PATH:-/app/config/agentic-operator-source.provenance.json}"',
        'MESH_DEPLOYMENT_COMPATIBILITY_REGISTRY_PATH: "${MESH_DEPLOYMENT_COMPATIBILITY_REGISTRY_PATH:-/app/config/deployment-compatibility.registry.json}"',
        'MESH_RELEASE_PROVENANCE_PATH: "${MESH_RELEASE_PROVENANCE_PATH:-/app/.mesh-runtime-state/release-provenance.json}"',
        'MESH_AUDIT_SINK_PROOF_PATH: "${MESH_AUDIT_SINK_PROOF_PATH:-}"',
        'MESH_AUDIT_SINK_CERTIFICATION_PATH: "${MESH_AUDIT_SINK_CERTIFICATION_PATH:-}"',
        'MESH_ON_CALL_DRILL_PATH: "${MESH_ON_CALL_DRILL_PATH:-}"',
        'MESH_POLICY_SIGNING_KEY: "${MESH_POLICY_SIGNING_KEY:-}"',
        'MESH_POLICY_SIGNING_KEY_PATH: "${MESH_POLICY_SIGNING_KEY_PATH:-}"',
        'MESH_BRAIN_ARTIFACT_URI_PREFIX: "${MESH_BRAIN_ARTIFACT_URI_PREFIX:-}"',
        'MESH_BRAIN_ARTIFACT_REGISTRY_PATH: "${MESH_BRAIN_ARTIFACT_REGISTRY_PATH:-}"',
        'MESH_BRAIN_ARTIFACT_UPLOAD_PROOF_PATH: "${MESH_BRAIN_ARTIFACT_UPLOAD_PROOF_PATH:-}"',
        'MESH_BRAIN_SERVING_BASE_URL: "${MESH_BRAIN_SERVING_BASE_URL:-}"',
        'MESH_BRAIN_SERVING_MODEL: "${MESH_BRAIN_SERVING_MODEL:-}"',
        'MESH_RUN_EXPORT_RETENTION_DAYS: "${MESH_RUN_EXPORT_RETENTION_DAYS:-30}"',
        'MESH_RUN_EXPORT_RETENTION_REVIEWED: "${MESH_RUN_EXPORT_RETENTION_REVIEWED:-0}"',
        'MESH_DESIGN_PARTNER_PACKET_PATH: "${MESH_DESIGN_PARTNER_PACKET_PATH:-}"',
        'MESH_FEATURE_FLAG_CREDENTIALS_AVAILABLE: "${MESH_FEATURE_FLAG_CREDENTIALS_AVAILABLE:-false}"',
        'MESH_INCIDENT_CREDENTIALS_AVAILABLE: "${MESH_INCIDENT_CREDENTIALS_AVAILABLE:-false}"',
        'E2E_AUTO_APPROVE: "${E2E_AUTO_APPROVE:-1}"',
        'MESH_E2E_OPERATOR_ROLES: "${MESH_E2E_OPERATOR_ROLES:-launcher,approver}"',
        'MESH_AGENT_OPERATOR_ROLES: "${MESH_AGENT_OPERATOR_ROLES:-approver}"',
    ),
    ".env.example": (
        "MESH_AUTHENTICATED_INGRESS_PROOF_PATH=.mesh-runtime-state/proofs/authenticated-ingress-deployment-proof.json",
        "MESH_DESIGN_PARTNER_PACKET_PATH=.mesh-runtime-state/proofs/design-partner-packet.json",
        "MESH_BACKUP_RESTORE_REHEARSAL_PATH=.mesh-runtime-state/backup-restore-rehearsal.json",
        "# MESH_POLICY_SIGNING_KEY_PATH=/run/secrets/mesh-policy-signing-key",
        "# MESH_POLICY_SIGNING_KEY=<target HMAC key from secret manager>",
        "# MESH_BRAIN_ARTIFACT_URI_PREFIX=s3://mesh-prod-artifacts/mesh-brain",
        "MESH_BRAIN_ARTIFACT_REGISTRY_PATH=.mesh-runtime-state/artifacts.json",
        "MESH_BRAIN_ARTIFACT_UPLOAD_PROOF_PATH=.mesh-runtime-state/mesh-brain-artifact-upload-proof.json",
        "# MESH_BRAIN_SERVING_BASE_URL=https://mesh-brain-serving.example.internal/v1",
        "# MESH_BRAIN_SERVING_MODEL=nvidia/nemotron-3-nano-4b",
        "MESH_RUN_EXPORT_RETENTION_DAYS=30",
        "MESH_RUN_EXPORT_RETENTION_REVIEWED=0",
        "MESH_RELEASE_PROVENANCE_PATH=.mesh-runtime-state/release-provenance.json",
        "# MESH_BUILD_IMAGE_DIGEST=sha256:<release image digest>",
        "MESH_ON_CALL_DRILL_PATH=.mesh-runtime-state/on-call-drill.json",
    ),
    "scripts/e2e_run_mesh.sh": (
        "E2E_AUTO_APPROVE",
        "MESH_E2E_OPERATOR_ID",
        "/api/runs/{run_id}/steer",
    ),
    "scripts/mesh_agent_operator.py": (
        "MESH_AGENT_OPERATOR_ID",
        "MESH_AGENT_OPERATOR_ROLES",
    ),
    "scripts/generate_release_provenance.py": (
        "mesh.release_provenance.v1",
        "--require-complete",
        "base_image_digests",
        "policy_hashes",
        "policy_lifecycle_signed",
        "--policy-signing-key-path",
        "MESH_POLICY_SIGNING_KEY_PATH",
        "_read_policy_signing_key",
        "connector_certification_registry",
        "deployment_compatibility_registry",
        "migration_version",
        "sbom_path",
        "vulnerability_scan_path",
        "ci_attestation",
        "_ci_attestation_record",
        "REQUIRED_CI_CHECKS",
        "REQUIRED_CI_ATTESTATION_PROVIDER",
        "provider:github-actions",
        "attestation_sha256",
        "_sbom_record",
        "_vulnerability_scan_record",
        "_valid_accepted_exception",
        "accepted_exception_count",
        "no_high_or_critical_findings",
        "real_release_image_sbom",
        "real_release_image_vulnerability_scan",
        "release_image_digest_match",
        "MESH_BUILD_IMAGE_DIGEST",
        "_attested_image_digest",
        "_attested_build_command",
        "_attested_base_image_digests",
    ),
    "scripts/collect_release_image_metadata.py": (
        "mesh.release_image_metadata.v1",
        "collect_release_image_metadata",
        "discover_base_images",
        "--dockerfile",
        "--base-image-args",
        "--require-complete-base-images",
        "expected_revision",
        "MESH_IMAGE_DIGEST",
    ),
    "scripts/generate_release_image_handoff.py": (
        "mesh.release_image_handoff.v1",
        "EXPORT_RELEASE_IMAGE",
        "--image-archive",
        "--image-digest",
        "--git-commit",
        "handoff_sha256",
    ),
    "scripts/verify_release_image_handoff.py": (
        "mesh.release_image_handoff_verification.v1",
        "mesh.release_image_handoff.v1",
        "EXPORT_RELEASE_IMAGE",
        "--manifest",
        "--image-archive",
        "--artifact-root",
        "--require-artifacts",
        "--image-ref",
        "--complete-release-provenance",
        "--env-output",
        "MESH_IMAGE",
        "MESH_STACK_IMAGE",
        "image_archive_sha256_match",
        "image_ref_digest_match",
        "env_output_artifacts_required",
        "ci_attestation_image_digest_match",
        "release_provenance_commit_match",
    ),
    ".github/workflows/release-image-handoff.yml": (
        "workflow_dispatch",
        "confirm_export",
        "EXPORT_RELEASE_IMAGE",
        "permissions:",
        "contents: read",
        "docker save",
        "gzip -n",
        "scripts/generate_release_image_handoff.py",
        "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02",
        "retention-days: ${{ inputs.retention_days }}",
        "python -m pip install uv",
        "pnpm --dir web exec playwright install --with-deps chromium",
        "pnpm run lint",
        "pnpm --dir web run build",
        "pnpm --dir meshapp/frontend run build",
    ),
    "scripts/generate_ci_attestation.py": (
        "mesh.ci_attestation.v1",
        "--require-github-actions",
        "GITHUB_ACTIONS=true",
        "GITHUB_RUN_ID",
        "attestation_sha256",
        "--check",
    ),
    "scripts/generate_release_assurance_rehearsal_inputs.py": (
        "mesh.release_assurance_rehearsal_inputs.v1",
        "raw-sbom.cdx.json",
        "raw-vulnerability-scan.json",
        "release-assurance-rehearsal",
    ),
    "scripts/generate_release_image_assurance.py": (
        "mesh.release_image_assurance.v1",
        "syft",
        "grype",
        "raw-sbom.syft.json",
        "scanner-sbom.syft.json",
        "binary-identity-corrections.json",
        "release-vulnerability-evidence.json",
        "raw-vulnerability-scan.grype.json",
        "normalize_release_assurance_artifacts.py",
        "normalize_syft_binary_identity_file",
        "--network",
        "--read-only",
        "--cap-drop=ALL",
        "--fail-on-blocking",
        "--exception-policy",
        "verified_vex_count",
        "unaccepted_blocking_finding_count",
    ),
    "shared/mesh_runtime/release_vulnerability_evidence.py": (
        "mesh.release_vulnerability_evidence.v1",
        "CVE-2026-15308",
        "CVE-2026-7017",
        "vulnerable_code_not_present",
        "7933f4bf7131aa4140750f9404f5de0aa2969ced",
        "4274e9112adf3fa57c7f9afa7c9b5c631456b18b7403cc627cc5027d02cdd2ae",
        "raw_scan_sha256",
        "raw_match_sha256",
        "--network",
        "--read-only",
        "--cap-drop=ALL",
    ),
    "scripts/normalize_syft_binary_identity.py": (
        "mesh.syft_binary_identity_correction.v1",
        'KNOWN_SYFT_VERSION = "1.44.0"',
        "https://github.com/anchore/syft/issues/5057",
        "pkg:generic/deno@",
        "pkg:pypi/deno@",
        "binary-classifier-cataloger",
        "python-installed-package-cataloger",
        "record_sha256",
        "executed_version",
        "removed_artifact_count",
    ),
    "scripts/normalize_release_assurance_artifacts.py": (
        "mesh.release_assurance_artifact_normalization.v1",
        "mesh.release_vulnerability_exceptions.v1",
        "bomFormat",
        "CycloneDX",
        "blocking_finding_count",
        "accepted_exception",
        "verified_vex",
        "--vulnerability-evidence",
        "unaccepted_blocking_finding_count",
        "--image-digest",
        "--fail-on-blocking",
        "--exception-policy",
        "--require-scan",
    ),
    "scripts/verify_release_runtime_binding.py": (
        "mesh.release_runtime_binding.v1",
        "MESH_IMAGE",
        "MESH_STACK_IMAGE",
        "MESH_BUILD_COMMIT",
        "MESH_BUILD_IMAGE_DIGEST",
        "--env-output",
        "--health-url",
        "--image-ref",
        "release_provenance_complete",
        "runtime_image_digest_match",
    ),
    "scripts/verify_release_artifact_bundle.py": (
        "mesh.release_artifact_bundle_verification.v1",
        "ci-attestation/ci-attestation.json",
        "release-provenance-draft/release-provenance-draft.json",
        "release-assurance-artifacts/release-assurance/sbom.cdx.json",
        "release-assurance-artifacts/release-assurance/vulnerability-scan.json",
        "verify_release_runtime_binding",
        "--expected-head",
        "--env-output",
        "MESH_RELEASE_PROVENANCE_PATH",
        "MESH_BUILD_IMAGE_DIGEST",
    ),
    "scripts/verify_pilot_clearance.py": (
        "mesh.pilot_clearance_audit.v1",
        "/api/health",
        "/api/readiness",
        "/api/pilot/go-no-go",
        "--expect-blocked",
        "expected_readiness_blockers_present",
        "expected_go_no_go_missing_present",
        "expected_readiness_blocker_details_present",
        "expected_go_no_go_missing_details_present",
        "expected_go_no_go_true_checks_present",
        "expected_go_no_go_observed_proof_details_present",
        "go_no_go_observed_proof_details",
        "prompt_to_artifact_checklist",
        "readiness_blocker_details",
        "go_no_go_missing_details",
        "unexpected_readiness_blockers_absent",
        "unexpected_go_no_go_missing_absent",
        "expect_blocked",
        "release_provenance_complete",
        "runtime_build_commit_match",
        "runtime_image_digest_match",
        "runtime_expected_head_valid",
        "runtime_build_commit_matches_expected_head",
    ),
    "docs/release-provenance.md": (
        "MESH_IMAGE_DIGEST",
        "MESH_SBOM_PATH",
        "MESH_VULNERABILITY_SCAN_PATH",
        "MESH_CI_ATTESTATION_PATH",
        "MESH_RELEASE_PROVENANCE_PATH",
        "MESH_BUILD_IMAGE_DIGEST",
        "scripts/verify_release_runtime_binding.py",
        "config/release-vulnerability-exceptions.json",
        "normalize_release_assurance_artifacts.py",
        "scripts/verify_mesh_brain_artifact_registry.py",
        "Policy Lifecycle Hashes",
        "MESH_POLICY_SIGNING_KEY",
        "mesh.ci_attestation.v1",
        "attestation_sha256",
        'provider: "github-actions"',
        "run_id",
        "MESH_IMAGE_DIGEST",
        "bomFormat: \"CycloneDX\"",
        "no_high_or_critical_findings",
        "release_image_digest_match",
        "real release-image scanner",
        "deployment_compatibility_registry",
        "deployment.compatibility",
        "Release Image Handoff",
        ".github/workflows/release-image-handoff.yml",
        "scripts/generate_release_image_handoff.py",
        "scripts/verify_release_image_handoff.py",
        "EXPORT_RELEASE_IMAGE",
        "--expect-blocked",
    ),
    "scripts/verify_authenticated_ingress.py": (
        "mesh.authenticated_ingress_rehearsal.v1",
        "operator_identity_required=True",
        "X-Mesh-Operator",
        "X-Mesh-Roles",
        "anonymous_run_creation_denied",
        "viewer_policy_simulation_accepted",
        "launcher_run_creation_accepted",
        "approver_approval_accepted",
        "admin_kill_switch_accepted",
    ),
    "scripts/verify_authenticated_ingress_deployment.py": (
        "mesh.authenticated_ingress_deployment_verification.v1",
        "--proof",
        "--expected-environment",
        "verify_authenticated_ingress_deployment_proof",
    ),
    "docs/authenticated-ingress.md": (
        "MESH_OPERATOR_IDENTITY_REQUIRED=1",
        "MESH_AUTHENTICATED_INGRESS_PROOF_PATH",
        "MESH_PUBLISH_HOST",
        "MESH_STATE_BACKEND=postgres",
        "MESH_BRAIN_ARTIFACT_URI_PREFIX",
        "MESH_BRAIN_SERVING_BASE_URL",
        "X-Mesh-Operator",
        "X-Mesh-Roles",
        "viewer",
        "launcher",
        "approver",
        "admin",
        "scripts/verify_authenticated_ingress.py",
        "scripts/verify_authenticated_ingress_deployment.py",
    ),
    "docs/reference-architectures.md": (
        "docker-compose.stack.yml",
        "docker-compose.prod.yml",
        "config/ownership.registry.json",
        "config/policy-lifecycle.manifest.json",
        "docs/deployment-compatibility.md",
        "docs/agentic-operator-core-import-plan.md",
        "docs/authenticated-ingress.md",
        "scripts/prod_smoke.sh",
        "scripts/verify_postgres_restart_proof.py",
        "scripts/generate_release_provenance.py",
        "Kubernetes Platform Team",
        "GPU And AI Infrastructure",
        "Regulated Enterprise",
        "Air-Gapped Or Offline-Adjacent",
    ),
    "docs/deployment-compatibility.md": (
        "validated",
        "supported",
        "recipe",
        "not planned",
        "ownership registry",
        "policy lifecycle",
        "evidence sufficiency",
        "threat-model register",
        "connector certification",
        "deployment-compatibility.registry.json",
        "verify_deployment_compatibility.py",
        "verify_ecs_fargate_promotion.py",
        "/api/deployment/compatibility",
        "deployment_compatibility_registry_reviewed",
        "failure modes",
        "/api/watchers/ownership",
        "Docker Compose",
        "Kubernetes",
        "agentic-operator-core-main/",
        "ECS/Fargate",
        "/api/readiness",
        "/api/failure-modes",
        "/api/pilot/go-no-go",
    ),
    "docs/agentic-operator-core-import-plan.md": (
        "agentic-operator-core-main/api/v1alpha1/agentworkload_types.go",
        "agentic-operator-core-main/api/v1alpha1/tenant_types.go",
        "agentic-operator-core-main/pkg/argo/",
        "agentic-operator-core-main/charts/",
        "AgentWorkload",
        "Tenant",
        "LiteLLM",
        "MCP",
        "Orbital Mesh authority",
    ),
    "config/ownership.registry.json": (
        "ownership.registry.v1",
        "namespace",
        "tenant_id",
        "customer_id",
        "customer_boundary",
        "approver_roles",
        "rollback_authority",
        "allowed_action_classes",
        "data_boundary",
        "reservoir_refs",
        "export_policy",
        "legal_action_scope",
    ),
    "config/threat-model.register.json": (
        "mesh.threat_model_register.v1",
        "finding_id",
        "owner",
        "decision",
        "expires_at",
        "compensating_control",
        "evidence_refs",
        "http_api",
        "webhooks",
        "otel_ingest",
        "proposal_lanes",
    ),
    "config/data-classification.policy.json": (
        "mesh.data_classification_policy.v1",
        "operational_signal",
        "secret_material",
        "application_log",
        "distributed_trace",
        "retention_days",
        "deletion_mode",
        "deletion_controls",
        "requires_redaction",
    ),
    "config/agentic-operator-source.provenance.json": (
        "mesh.agentic_operator_source_provenance.v1",
        "agentic-operator-core-main/api/v1alpha1/agentworkload_types.go",
        "agentic-operator-core-main/api/v1alpha1/tenant_types.go",
        "Apache-2.0",
        "source-input-only",
        "wholesale_copy_allowed",
        "required_authority_gates",
        "forbidden_credentials",
    ),
    "config/deployment-compatibility.registry.json": (
        "mesh.deployment_compatibility.registry.v1",
        "docker_compose",
        "kubernetes",
        "ecs_fargate",
        "next_validated_target",
        "verify_ecs_fargate_promotion.py",
        "promotion_blockers",
        "release_packet_required",
        "authority_boundary",
    ),
    "shared/mesh_runtime/ownership.py": (
        "build_ownership_boundary",
        "ownership_registry_ready",
        "ownership-boundary.schema.json",
        "ownership-registry.schema.json",
    ),
    "config/policy-lifecycle.manifest.json": (
        "policy.lifecycle.manifest.v1",
        "effective_from",
        "review_expires_at",
        "rollback_ref",
        "risk_tier",
    ),
    "config/failure-mode.library.json": (
        "mesh.failure_mode_library.registry.v1",
        "denied_namespace",
        "stale_kubeconfig",
        "llm_unavailable",
        "audit_sink_unavailable",
        "queue_backpressure",
        "ui://failure-mode",
    ),
    "shared/mesh_runtime/policy_lifecycle.py": (
        "build_policy_lifecycle_packet",
        "policy_lifecycle_ready",
        "hmac-sha256",
        "policy-lifecycle-packet.schema.json",
    ),
    "shared/mesh_runtime/pilot_signoff.py": (
        "mesh.pilot_signoff.v1",
        "pilot.go_no_go.v1",
        "mesh.pilot_signoff_verification.v1",
        "hmac-sha256",
        "AUTHORIZED_SIGNOFF_ROLES",
        "expected_release_provenance_sha",
        "go_no_go_packet_hash_matches",
        "pilot-signoff.schema.json",
    ),
    "scripts/verify_pilot_signoff.py": (
        "mesh.pilot_signoff_verification.v1",
        "MESH_PILOT_SIGNOFF_KEY",
        "--build-output",
        "--expected-release-provenance-sha",
        "--go-no-go",
        "--operator-id",
        "--signoff",
        "decision_go",
    ),
    "shared/mesh_runtime/design_partner.py": (
        "mesh.design_partner_packet.v1",
        "mesh.design_partner_packet_verification.v1",
        "design_partner_packet_ready",
        "design-partner-packet.schema.json",
    ),
    "scripts/verify_design_partner_packet.py": (
        "mesh.design_partner_packet_verification.v1",
        "--packet",
        "--expected-go-no-go-sha",
        "--expected-release-provenance-sha",
        "verify_design_partner_packet",
    ),
    "shared/mesh_runtime/operator_handoff.py": (
        "mesh.operator_handoff.v1",
        "build_operator_handoff",
        "operator-handoff.schema.json",
        "OPERATOR_HANDOFF_URGENCIES",
    ),
    "shared/mesh_runtime/postmortem_review.py": (
        "mesh.postmortem_review.v1",
        "build_postmortem_review",
        "postmortem-review.schema.json",
        "POSTMORTEM_REVIEW_VERDICTS",
    ),
    "shared/mesh_runtime/override_review.py": (
        "mesh.override_review.v1",
        "build_override_review",
        "override-review.schema.json",
        "OVERRIDE_REVIEW_COMMANDS",
        "OVERRIDE_REVIEW_VERDICTS",
    ),
    "docs/production-hardening-records.md": (
        "Operator Handoff Evidence",
        "mesh.operator_handoff.v1",
        "operator_handoff_recorded",
        "handoff_records",
        "Override Review Evidence",
        "mesh.override_review.v1",
        "override_review_recorded",
        "override_review_records",
        "Postmortem Review Evidence",
        "mesh.postmortem_review.v1",
        "postmortem_review_recorded",
        "postmortem_review_records",
        "Backup Restore Rehearsal Evidence",
        "mesh.backup_restore_rehearsal.v1",
        "backup_restore_rehearsal_verified",
        "Migration Rehearsal Evidence",
        "mesh.migration_rehearsal.v1",
        "migration_rehearsal",
        "On-Call Drill Evidence",
        "mesh.on_call_drill.v1",
        "on_call_drill_verified",
        "Failure Mode Library",
        "mesh.failure_mode_library.v1",
        "failure_mode_library_configured",
        "GET /api/failure-modes",
        "Threat Model Register",
        "mesh.threat_model_register.v1",
        "threat_model_register_reviewed",
        "Data Classification Policy",
        "mesh.data_classification_policy.v1",
        "data_classification_policy_reviewed",
        "Agentic Operator Source Provenance",
        "mesh.agentic_operator_source_provenance.v1",
        "agentic_operator_source_provenance_recorded",
        "Deployment Compatibility Registry",
        "mesh.deployment_compatibility.v1",
        "deployment_compatibility_registry_reviewed",
        "GET /api/deployment/compatibility",
        "Evaluation Kit Packet",
        "mesh.evaluation_kit_packet.v1",
        "generate_evaluation_kit_packet.py",
        "Benchmark Run Artifact Verification",
        "mesh.benchmark_run_artifacts_verification.v1",
        "verify_benchmark_run_artifacts.py",
        "Watcher Ownership Evidence",
        "mesh.watcher_ownership.v1",
        "GET /api/watchers/ownership",
        "Approval Queue Evidence",
        "mesh.approval_queue.v1",
        "GET /api/approvals",
        "Procurement And Security Package",
        "mesh.procurement_security_package.v1",
        "procurement_security_package_verified",
        "Public Proof Package",
        "mesh.public_proof_package.v1",
        "public_proof_package_verified",
        "Load Concurrency Rehearsal",
        "mesh.load_concurrency_rehearsal.v1",
        "load_concurrency_rehearsal_verified",
        "Live Signal Ingest Proof",
        "mesh.production_live_proof_bundle.v1",
        "mesh.watch_mode_proof.v1",
        "mesh.incident_coverage_proof.v1",
        "verify_production_autonomy_clearance.py",
        "verify_watch_mode_proof.py",
        "verify_incident_coverage_proof.py",
        "Provider Action Scope",
        "mesh.provider_action_scope_proof.v1",
        "verify_provider_action_scopes.py",
        "Provider Adapter Proof",
        "mesh.provider_adapter_proof.v1",
        "verify_provider_adapter_proof.py",
        "Audit Sink Certification",
        "mesh.audit_sink_certification.v1",
        "external_audit_sink_certification_verified",
        "Mesh Orchestration Topology",
        "mesh.orchestration_topology_profile.v1",
        "mesh.orchestration_topology_resolution.v1",
        "orchestration_topology_profile_configured",
        "mesh.orchestration_topology_drill.v1",
        "orchestration_topology_drill_verified",
    ),
    "config/orchestration-topology.profile.json": (
        "mesh.orchestration_topology_profile.v1",
        "centralized",
        "source_refs",
        "trust_ladder",
    ),
    "shared/mesh_runtime/orchestration_topology.py": (
        "mesh.orchestration_topology_profile.v1",
        "mesh.orchestration_topology_resolution.v1",
        "resolve_orchestration_topology",
        "SOURCE_EVIDENCE_VERSION",
    ),
    "shared/mesh_runtime/orchestration_drill.py": (
        "mesh.orchestration_topology_drill.v1",
        "mesh.orchestration_topology_drill_verification.v1",
        "build_orchestration_topology_drill_packet",
        "orchestration_topology_drill_ready",
        "verify_orchestration_topology_drill",
    ),
    "scripts/generate_orchestration_topology_drill.py": (
        "mesh.orchestration_topology_drill.v1",
        "--run-export",
        "--operator-approval-recorded",
        "build_orchestration_topology_drill_packet",
    ),
    "scripts/verify_orchestration_topology_drill.py": (
        "mesh.orchestration_topology_drill_verification.v1",
        "--proof",
        "verify_orchestration_topology_drill",
    ),
    "config/procurement-security.package.json": (
        "mesh.procurement_security_package.v1",
        "sso_identity",
        "audit_export",
        "retention_controls",
        "data_boundaries",
        "deployment_modes",
        "security_answers",
        "support_escalation",
        "known_limits",
        "raw_secret_material_present",
    ),
    "shared/mesh_runtime/approval_queue.py": (
        "mesh.approval_queue.v1",
        "build_approval_queue_packet",
        "approval-queue.schema.json",
        "approval_state",
    ),
    "shared/mesh_runtime/procurement_security.py": (
        "mesh.procurement_security_package.v1",
        "procurement_security_package_ready",
        "verify_procurement_security_package",
        "procurement-security-package.schema.json",
        "REQUIRED_PROCUREMENT_SECTIONS",
    ),
    "config/public-proof.package.json": (
        "mesh.public_proof_package.v1",
        "benchmark_report",
        "architecture_paper",
        "demo_dataset",
        "run_export",
        "limitations_statement",
        "raw_secret_material_present",
    ),
    "shared/mesh_runtime/public_proof.py": (
        "mesh.public_proof_package.v1",
        "public_proof_package_ready",
        "verify_public_proof_package",
        "public-proof-package.schema.json",
        "REQUIRED_PUBLIC_PROOF_COMPONENTS",
    ),
    "shared/mesh_runtime/load_concurrency.py": (
        "mesh.load_concurrency_rehearsal.v1",
        "mesh.load_concurrency_verification.v1",
        "load_concurrency_rehearsal_ready",
        "verify_load_concurrency_rehearsal",
        "load-concurrency-rehearsal.schema.json",
    ),
    "shared/mesh_runtime/watch_mode_proof.py": (
        "mesh.watch_mode_proof.v1",
        "mesh.watch_mode_proof_verification.v1",
        "verify_watch_mode_proof",
        "watch-mode-proof.schema.json",
        "kill_switch_paused_watchers",
        "third_party_replay_ref_present",
    ),
    "scripts/verify_watch_mode_proof.py": (
        "mesh.watch_mode_proof_verification.v1",
        "--proof",
        "--require-live",
        "verify_watch_mode_proof",
    ),
    "shared/mesh_runtime/incident_coverage.py": (
        "mesh.incident_coverage_proof.v1",
        "mesh.incident_coverage_verification.v1",
        "verify_incident_coverage_proof",
        "incident-coverage-proof.schema.json",
        "REQUIRED_INCIDENT_CLASSES",
        "false_positive_controls",
    ),
    "scripts/verify_incident_coverage_proof.py": (
        "mesh.incident_coverage_verification.v1",
        "--proof",
        "--require-live",
        "verify_incident_coverage_proof",
    ),
    "scripts/verify_load_concurrency_rehearsal.py": (
        "mesh.load_concurrency_verification.v1",
        "--proof",
        "verify_load_concurrency_rehearsal",
    ),
    "scripts/capture_production_live_proof_bundle.py": (
        "mesh.production_live_proof_capture.v1",
        "--base-url",
        "--target-scenario-key",
        "--repeat-scenario-key",
        "generate_production_live_proof_bundle.py",
    ),
    "scripts/generate_production_live_proof_bundle.py": (
        "mesh.production_live_proof_bundle.v1",
        "--target-run-json",
        "--allow-partial",
        "--clean-env-recreated",
        "--fresh-image-built",
        "verify_production_autonomy_clearance",
    ),
    "scripts/verify_production_target_proof.py": (
        "mesh.production_target_verification.v1",
        "--proof",
        "--require-live",
        "verify_production_target_proof",
    ),
    "scripts/run_load_concurrency_rehearsal.py": (
        "mesh.load_concurrency_rehearsal.v1",
        "--database-url",
        "run_rehearsal",
        "tenant_active_run_limit",
    ),
    "shared/mesh_runtime/provider_adapter.py": (
        "mesh.provider_adapter_proof.v1",
        "mesh.provider_adapter_verification.v1",
        "provider_adapter_proof_ready",
        "verify_provider_adapter_proof",
        "provider-adapter-proof.schema.json",
        "feature_flag_provider",
        "incident_provider",
    ),
    "shared/mesh_runtime/provider_action_scope.py": (
        "mesh.provider_action_scope_proof.v1",
        "mesh.provider_action_scope_verification.v1",
        "verify_provider_action_scope_proof",
        "provider-action-scope-proof.schema.json",
        "approval_required",
        "secret_material_exposed",
    ),
    "scripts/verify_provider_adapter_proof.py": (
        "mesh.provider_adapter_verification.v1",
        "--adapter-id",
        "--proof",
        "verify_provider_adapter_proof",
    ),
    "scripts/verify_provider_action_scopes.py": (
        "mesh.provider_action_scope_verification.v1",
        "--proof",
        "--require-live",
        "verify_provider_action_scope_proof",
    ),
    "config/connector-certification.registry.json": (
        "connector.certification.registry.v1",
        "connector_id",
        "required_before",
        "authority_posture",
        "credential_policy",
        "credential_boundary",
        "service_account_ref",
        "production_actuator_credentials_allowed",
        "repo_write_credentials_allowed",
        "break_glass_recording_required",
        "degraded_behavior",
        "proposal-only",
        "pilot-ready",
    ),
    "shared/mesh_runtime/connector_certification.py": (
        "build_connector_certification_matrix",
        "connector_certification_registry_ready",
        "mesh.connector_certification.v1",
        "proposal_lane_production_actuator_credentials_present",
        "proposal_lane_repo_write_credentials_present",
        "connector-certification-matrix.schema.json",
        "connector-certification-registry.schema.json",
    ),
    "shared/mesh_runtime/evidence_sufficiency.py": (
        "evaluate_evidence_sufficiency",
        "mesh.evidence_sufficiency.v1",
        "minimum_evidence_count",
        "evidence-sufficiency.schema.json",
    ),
    "shared/mesh_runtime/failure_modes.py": (
        "mesh.failure_mode_library.v1",
        "build_failure_mode_library_packet",
        "failure_mode_library_ready",
        "REQUIRED_FAILURE_MODES",
        "failure-mode-library.schema.json",
        "failure-mode-library-packet.schema.json",
    ),
    "shared/mesh_runtime/threat_model.py": (
        "mesh.threat_model_register.v1",
        "mesh.threat_model_register_verification.v1",
        "verify_threat_model_register",
        "threat_model_register_ready",
        "threat-model-register.schema.json",
    ),
    "shared/mesh_runtime/data_classification.py": (
        "mesh.data_classification_policy.v1",
        "mesh.data_classification_policy_verification.v1",
        "verify_data_classification_policy",
        "data_classification_policy_ready",
        "data-classification-policy.schema.json",
    ),
    "shared/mesh_runtime/agentic_operator_provenance.py": (
        "mesh.agentic_operator_source_provenance.v1",
        "mesh.agentic_operator_source_provenance_verification.v1",
        "verify_agentic_operator_source_provenance",
        "agentic_operator_source_provenance_ready",
        "agentic-operator-source-provenance.schema.json",
        "REQUIRED_AUTHORITY_GATES",
        "FORBIDDEN_CREDENTIALS",
    ),
    "shared/mesh_runtime/deployment_compatibility.py": (
        "mesh.deployment_compatibility.v1",
        "mesh.deployment_compatibility_verification.v1",
        "build_deployment_compatibility_matrix",
        "verify_deployment_compatibility_registry",
        "deployment_compatibility_registry_ready",
        "deployment-compatibility-registry.schema.json",
        "deployment-compatibility-matrix.schema.json",
        "REQUIRED_TARGETS",
    ),
    "shared/mesh_runtime/ecs_fargate.py": (
        "mesh.ecs_fargate_promotion_proof.v1",
        "mesh.ecs_fargate_promotion_verification.v1",
        "verify_ecs_fargate_promotion_proof",
        "ecs-fargate-promotion-proof.schema.json",
        "no_raw_secret_material",
        "release_provenance_complete",
        "postgres_persistence_proved",
    ),
    "shared/mesh_runtime/evaluation_kit.py": (
        "mesh.evaluation_kit_packet.v1",
        "mesh.evaluation_kit_packet_verification.v1",
        "verify_evaluation_kit_packet",
        "evaluation-kit-packet.schema.json",
        "REQUIRED_BENCHMARK_ARTIFACTS",
    ),
    "scripts/verify_threat_model_register.py": (
        "mesh.threat_model_register.v1",
        "--register",
        "verify_threat_model_register",
    ),
    "scripts/verify_data_classification_policy.py": (
        "mesh.data_classification_policy.v1",
        "--policy",
        "verify_data_classification_policy",
    ),
    "scripts/verify_agentic_operator_source_provenance.py": (
        "mesh.agentic_operator_source_provenance.v1",
        "--provenance",
        "verify_agentic_operator_source_provenance",
    ),
    "scripts/verify_deployment_compatibility.py": (
        "mesh.deployment_compatibility_verification.v1",
        "--registry",
        "verify_deployment_compatibility_registry",
    ),
    "scripts/verify_ecs_fargate_promotion.py": (
        "mesh.ecs_fargate_promotion_verification.v1",
        "--proof",
        "verify_ecs_fargate_promotion_proof",
    ),
    "scripts/generate_evaluation_kit_packet.py": (
        "mesh.evaluation_kit_packet.v1",
        "build_evaluation_kit_packet",
        "verify_run_export_retrieval",
        "services.benchmark",
    ),
    "scripts/verify_evaluation_kit_packet.py": (
        "mesh.evaluation_kit_packet_verification.v1",
        "--packet",
        "verify_evaluation_kit_packet",
    ),
    "shared/mesh_runtime/benchmark_artifacts.py": (
        "mesh.benchmark_run_artifacts_verification.v1",
        "verify_benchmark_run_artifacts",
        "benchmark-run-artifacts-verification.schema.json",
        "REQUIRED_BENCHMARK_ARTIFACTS",
        "unsafe_action_rate_ok",
    ),
    "scripts/verify_benchmark_run_artifacts.py": (
        "mesh.benchmark_run_artifacts_verification.v1",
        "--run-dir",
        "--expected-scenario-id",
        "verify_benchmark_run_artifacts",
    ),
    "shared/mesh_runtime/watcher_ownership.py": (
        "mesh.watcher_ownership.v1",
        "build_watcher_ownership_packet",
        "watcher-ownership.schema.json",
        "build_ownership_boundary",
        "registry_path",
    ),
    "scripts/verify_failure_mode_library.py": (
        "mesh.failure_mode_library.v1",
        "--library",
        "build_failure_mode_library_packet",
    ),
    "shared/mesh_runtime/timeline_proof.py": (
        "build_timeline_proof",
        "mesh.timeline_proof.v1",
        "time_unix_nano",
        "payload_sha256",
        "latest_event_proof_valid",
        "timeline-proof.schema.json",
    ),
    "shared/mesh_runtime/run_admission.py": (
        "build_run_admission",
        "mesh.run_admission.v1",
        "tenant_active_run_quota",
        "target_lock_held",
        "run-admission.schema.json",
    ),
    "shared/mesh_runtime/audit_sink.py": (
        "mesh.audit_sink_proof.v1",
        "mesh.audit_sink_contract_verification.v1",
        "audit_sink_proof_ready",
        "DURABLE_AUDIT_URI_SCHEMES",
        "break_glass_recording_required",
        "runtime-secret",
        "audit-sink-proof.schema.json",
    ),
    "scripts/verify_audit_sink_contract.py": (
        "mesh.audit_sink_contract_verification.v1",
        "--proof",
        "verify_audit_sink_proof",
        "append-only proof",
    ),
    "shared/mesh_runtime/audit_sink_certification.py": (
        "mesh.audit_sink_certification.v1",
        "mesh.audit_sink_certification_verification.v1",
        "audit_sink_certification_ready",
        "verify_audit_sink_certification",
        "audit-sink-certification.schema.json",
        "compliance_reliance_allowed",
    ),
    "scripts/verify_audit_sink_certification.py": (
        "mesh.audit_sink_certification_verification.v1",
        "--certification",
        "--proof",
        "--registry",
        "verify_audit_sink_certification",
    ),
    "shared/mesh_runtime/credential_rotation.py": (
        "mesh.credential_rotation_proof.v1",
        "mesh.credential_rotation_verification.v1",
        "verify_credential_rotation_proof",
        "credential-rotation-proof.schema.json",
        "break_glass_recording_rehearsed",
        "secret_material_absent",
    ),
    "scripts/verify_credential_rotation.py": (
        "mesh.credential_rotation_verification.v1",
        "--connector-id",
        "--proof",
        "verify_credential_rotation_proof",
    ),
    "docs/pilot-slo-error-budget.md": (
        "/api/health",
        "/api/readiness",
        "/api/agent/slo",
        "/metrics",
        "/api/pilot/go-no-go",
        "scripts/prod_smoke.sh",
        "scripts/verify_authenticated_ingress.py",
        "scripts/verify_authenticated_ingress_deployment.py",
        "scripts/verify_failure_mode_library.py",
        "scripts/verify_threat_model_register.py",
        "scripts/verify_data_classification_policy.py",
        "scripts/verify_agentic_operator_source_provenance.py",
        "scripts/generate_evaluation_kit_packet.py",
        "scripts/verify_evaluation_kit_packet.py",
        "scripts/verify_benchmark_run_artifacts.py",
        "scripts/verify_postgres_restart_proof.py",
        "scripts/generate_release_provenance.py",
        "Hard Stop Conditions",
        "Error Budget",
        "scripts/verify_audit_sink_contract.py",
        "scripts/verify_credential_rotation.py",
        "scripts/verify_on_call_drill.py",
        "scripts/verify_design_partner_packet.py",
    ),
    "docs/post-training/runtime.md": (
        "MESH_BRAIN_ARTIFACT_URI_PREFIX",
        "MESH_BRAIN_ARTIFACT_REGISTRY_PATH",
        "MESH_BRAIN_ARTIFACT_UPLOAD_PROOF_PATH",
        "MESH_BRAIN_SERVING_BASE_URL",
        "MESH_BRAIN_SERVING_MODEL",
        "build_production_artifact_ref()",
        "verify_production_artifact_record()",
        "scripts/verify_mesh_brain_artifact_registry.py",
        "mesh.artifact_upload_proof.v1",
        "prior stable live-serving smoke",
        "durable object-storage URIs",
        "curated_quality_training_passed",
        "quality_source_coverage",
        "evaluate_quality_dataset_provenance()",
        "rollback metadata",
        "operator approval",
    ),
    "mesh_brain/artifact_registry.py": (
        "DURABLE_ARTIFACT_URI_SCHEMES",
        "build_production_artifact_ref",
        "verify_artifact_upload_registry",
        "mesh.mesh_brain_artifact_registry_proof.v1",
        "verify_production_artifact_record",
        "upload_proofs_present",
        "production artifact URI must use durable object storage scheme",
    ),
    "scripts/verify_mesh_brain_artifact_registry.py": (
        "mesh.mesh_brain_artifact_registry_proof.v1",
        "--require-upload-proof",
        "mesh.artifact_upload_proof.v1",
        "verify_artifact_upload_registry",
    ),
    "scripts/purge_run_exports.py": (
        "mesh.run_export.v1",
        "--apply",
        "retention.delete_after",
        "would_delete",
        "run_exports",
    ),
    "shared/mesh_runtime/run_export_retrieval.py": (
        "mesh.run_export_retrieval.v1",
        "verify_run_export_retrieval",
        "mesh.run_export_archive.v1",
        "package_checksum_valid",
        "secret_fields_redacted",
        "archive_vault_documents_present",
        "run-export-retrieval.schema.json",
    ),
    "scripts/verify_run_export_retrieval.py": (
        "mesh.run_export_retrieval.v1",
        "--package",
        "--archive",
        "verify_run_export_retrieval",
    ),
    "shared/mesh_runtime/run_export_upload.py": (
        "mesh.run_export_upload_proof.v1",
        "mesh.run_export_upload_verification.v1",
        "verify_run_export_upload_proof",
        "DURABLE_RUN_EXPORT_URI_SCHEMES",
        "package_provider_matches",
        "archive_provider_matches",
        "restore_tested",
        "run-export-upload-proof.schema.json",
    ),
    "scripts/verify_run_export_upload.py": (
        "mesh.run_export_upload_verification.v1",
        "--package",
        "--archive",
        "--proof",
        "verify_run_export_upload_proof",
    ),
    "shared/mesh_runtime/authenticated_ingress.py": (
        "mesh.authenticated_ingress_deployment_proof.v1",
        "mesh.authenticated_ingress_deployment_verification.v1",
        "authenticated_ingress_deployment_ready",
        "expected_environment",
        "environment_matches_expected",
        "authenticated-ingress-deployment-proof.schema.json",
    ),
    "shared/mesh_runtime/backup_restore.py": (
        "mesh.backup_restore_rehearsal.v1",
        "mesh.backup_restore_verification.v1",
        "verify_backup_restore_rehearsal",
        "expected_environment",
        "expected_state_backend",
        "environment_matches_expected",
        "state_backend_matches_expected",
        "BACKUP_RESTORE_COMPONENTS",
        "backup-restore-rehearsal.schema.json",
    ),
    "scripts/verify_backup_restore_rehearsal.py": (
        "mesh.backup_restore_verification.v1",
        "--proof",
        "--expected-environment",
        "--expected-state-backend",
        "verify_backup_restore_rehearsal",
    ),
    "scripts/run_backup_restore_rehearsal.py": (
        "mesh.backup_restore_rehearsal.v1",
        "--database-url",
        "run_rehearsal",
        "BACKUP_RESTORE_COMPONENTS",
    ),
    "shared/mesh_runtime/migration_rehearsal.py": (
        "mesh.migration_rehearsal.v1",
        "mesh.migration_rehearsal_verification.v1",
        "build_migration_rehearsal_packet",
        "migration_rehearsal_inventory",
        "verify_migration_rehearsal",
        "migration-rehearsal.schema.json",
    ),
    "scripts/generate_migration_rehearsal.py": (
        "mesh.migration_rehearsal.v1",
        "--rolled-back",
        "--destructive-changes-reviewed",
        "build_migration_rehearsal_packet",
        "verify_migration_rehearsal",
    ),
    "scripts/run_postgres_migration_rehearsal.py": (
        "mesh.migration_rehearsal.v1",
        "MESH_MIGRATION_REHEARSAL_DATABASE_URL",
        "--allow-existing-schema",
        "--allow-destructive-statements",
        "run_rehearsal",
        "verify_migration_rehearsal",
    ),
    "scripts/verify_migration_rehearsal.py": (
        "mesh.migration_rehearsal_verification.v1",
        "--proof",
        "--expected-version",
        "--expected-combined-sha256",
        "verify_migration_rehearsal",
    ),
    "shared/mesh_runtime/on_call_drill.py": (
        "mesh.on_call_drill.v1",
        "mesh.on_call_drill_verification.v1",
        "verify_on_call_drill",
        "on-call-drill.schema.json",
        "provider_key_break_glass_recorded",
        "state_restore_verified",
    ),
    "scripts/verify_on_call_drill.py": (
        "mesh.on_call_drill_verification.v1",
        "--proof",
        "--expected-environment",
        "verify_on_call_drill",
    ),
    "SECURITY.md": (
        "Reporting Vulnerabilities",
        "MESH_OPERATOR_IDENTITY_REQUIRED=1",
        "MESH_FORCE_APPROVAL_GATE=1",
        "complete release provenance",
    ),
    ".github/CODEOWNERS": (
        "/services/control_plane.py",
        "/control_plane_server.py",
        "/shared/mesh_runtime/schemas/",
        "/policies/",
    ),
    ".github/dependabot.yml": (
        'package-ecosystem: "github-actions"',
        'package-ecosystem: "npm"',
        'package-ecosystem: "pip"',
        'package-ecosystem: "cargo"',
        'directory: "/latent-mesh/LatentMAS"',
    ),
    ".github/workflows/security.yml": (
        "Security Audit",
        "cron:",
        "verify_security_audit_readiness.py --json",
        "actions/dependency-review-action@",
        "GITLEAKS_LINUX_X64_SHA256",
        "gitleaks detect --source=.",
        "ghcr.io/google/osv-scanner@sha256:",
        "osv-lockfile-scan.json",
        "pnpm --dir web audit --audit-level high --json",
        "pnpm-audit*.json",
        "GHAS_DEPENDENCY_REVIEW_ON_PRIVATE",
        "github/codeql-action/init@",
        "ossf/scorecard-action@",
        "OPENSSF_SCORECARD_ON_PRIVATE",
    ),
    ".github/workflows/ci.yml": (
        "permissions:",
        "contents: read",
        "python -m pip install uv",
        "pnpm --dir web exec playwright install --with-deps chromium",
        "pnpm run lint",
        "pnpm --dir web run build",
        "pnpm --dir meshapp/frontend run build",
        "cryptography>=48.0.1,<49",
        "tests.test_perennial_materialization",
        "tests.test_darkharness_packet",
        "tests.test_darkharness_policy",
        "tests.test_darkharness_export_path",
        "tests.test_darkharness_live_verifier",
        "docker build",
        "collect_release_image_metadata.py",
        'SYFT_VERSION: "1.44.0"',
        "SYFT_DEB_SHA256",
        'GRYPE_VERSION: "0.112.0"',
        "GRYPE_DEB_SHA256",
        "sha256sum -c -",
        "generate_release_image_assurance.py",
        "release-assurance-artifacts",
        "release-provenance-draft",
        "--image-digest \"$MESH_IMAGE_DIGEST\"",
        "--require-github-actions",
    ),
    ".github/workflows/repo-patch-service-image-release.yml": (
        "Repo patch service image release",
        "workflow_dispatch:",
        "if: github.event_name == 'workflow_dispatch'",
        "packages: write",
        "id-token: write",
        "attestations: write",
        "artifact-metadata: write",
        "ref: ${{ github.sha }}",
        "persist-credentials: false",
        "Verify release platform preconditions before build",
        "REPO_PATCH_GITHUB_ATTESTATIONS_ENABLED",
        "REPO_PATCH_ACTIONS_ARTIFACT_STORAGE_READY",
        "pnpm run lint",
        "mesh_control_plane)",
        "repo_patch_authority)",
        "repo_patch_verifier)",
        "generate_release_image_assurance.py",
        "unaccepted_blocking_finding_count == 0",
        "mesh.image_source_binding.v1",
        "org.opencontainers.image.revision",
        "image-source-binding",
        "base-image-digest.args",
        "image-materials-binding",
        "Authenticate to GHCR only after all scans pass",
        "actions/attest@a1948c3f048ba23858d222213b7c278aabede763",
        "generate_repo_patch_service_image_bundle.py",
        "raw-vulnerability-scan.grype.json",
        "release-vulnerability-evidence.json",
        "verify_repo_patch_service_image_bundle.py",
        "Re-resolve registry digests",
        "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02",
    ),
    "Dockerfile": (
        "python:3.13.14-slim-trixie",
        "golang:1.26.5-bookworm",
        "DOCKER_CLI_VERSION=29.6.1",
        "DOCKER_CLI_GIT_COMMIT=8900f1d330cb39e93e16d780a26bff1d7e07ba03",
        "DOCKER_CLI_SOURCE_SHA256=74d14dd212b07cd3328989dc6a029dde2ebbe6a878199eaaafad54916f456194",
        "github.com/docker/cli/archive/refs/tags/v${DOCKER_CLI_VERSION}.tar.gz",
        "KUBECTL_VERSION=v1.36.2",
        "HERMES_AGENT_REF=7c1a029553d87c43ecff8a3821336bc95872213b",
        "KUBERNETES_SRC_SHA512",
        "make WHAT=cmd/kubectl",
        "CGO_ENABLED=0",
        "./scripts/build/binary",
        "sha256sum -c -",
        "sha512sum -c -",
        "uv venv venv --python /usr/local/bin/python3",
        "cryptography>=48.0.1,<49",
        "deno>=2.8.1,<3",
        "rm -f /usr/local/bin/uv /usr/local/bin/uvx",
        "apt-get purge -y --auto-remove curl git git-man",
        "org.opencontainers.image.source",
        "org.opencontainers.image.revision",
        "org.opencontainers.image.version",
    ),
    "docker/repo-patch-authority.Dockerfile": (
        "python:3.13.14-alpine3.24",
        "ca-certificates curl git",
        "apk del curl",
        "PYTHON_HTML_PARSER_BACKPORT_COMMIT=7933f4bf7131aa4140750f9404f5de0aa2969ced",
        "PYTHON_HTML_PARSER_BACKPORT_SHA256=4274e9112adf3fa57c7f9afa7c9b5c631456b18b7403cc627cc5027d02cdd2ae",
        "cryptography==${CRYPTOGRAPHY_VERSION}",
        "repo-patch-verifier-response-v2.schema.json",
        "services.actuators.repo_patch_authority_service",
        "org.opencontainers.image.source",
        "org.opencontainers.image.revision",
        "org.opencontainers.image.version",
    ),
    "docker/repo-patch-verifier.Dockerfile": (
        "verifier-python-dependencies",
        "verifier-python-backport",
        "PYTHON_HTML_PARSER_BACKPORT_COMMIT=7933f4bf7131aa4140750f9404f5de0aa2969ced",
        "PYTHON_HTML_PARSER_BACKPORT_SHA256=4274e9112adf3fa57c7f9afa7c9b5c631456b18b7403cc627cc5027d02cdd2ae",
        "cryptography==${CRYPTOGRAPHY_VERSION}",
        "repo-patch-verifier-response-v2.schema.json",
        "services.actuators.repo_patch_verifier_service",
        "org.opencontainers.image.source",
        "org.opencontainers.image.revision",
        "org.opencontainers.image.version",
    ),
    "shared/mesh_runtime/repo_patch_service_image_bundle.py": (
        "mesh.repo_patch_service_image_bundle.v1",
        "mesh_control_plane",
        "repo_patch_authority",
        "repo_patch_verifier",
        "mesh-repo-patch-verifier-receipt-ed25519-v2",
        "raw_vulnerability_scan_path",
        "vulnerability_evidence_path",
        "image_metadata_path",
        "_image_metadata_bound",
        "valid_verified_vex_summary",
        "unaccepted_blocking_finding_count",
        "provider\") == \"github-actions",
        "REQUIRED_CI_ATTESTATION_CHECKS",
        "MESH_BUILD_COMMIT",
    ),
    "docs/darkharness-operator-runbook.md": (
        "/api/runs/{run_id}/darkharness-packet",
        "/api/darkharness/pilot-packet",
        "scripts/verify_darkharness_live_packet.py --json",
        "policy_violation:",
        "materialization_failed:",
        "registry_invalid:",
        "rollback_drill_run_export_present",
        "Postgres remains authoritative",
        "MESH_DARKHARNESS_CLASSICAL_SIGNING_KEY_PATH",
        "Evidence Adapter Coverage",
        "trust-ladder ceiling",
    ),
    "docs/perennial-darkmesh-architecture.md": (
        "MESH_DARKHARNESS_CLASSICAL_SIGNING_KEY_PEM",
        "MESH_DARKHARNESS_CLASSICAL_SIGNING_KEY_PATH",
        "Ed25519",
        "PQC signatures, KEM, and ZK",
        "selective disclosure remain proposed hooks",
        "materialize_runtime_evidence_action_records",
    ),
    "shared/mesh_runtime/perennial/runtime_evidence.py": (
        "materialize_runtime_evidence_action_records",
        "darkharness_remediation_safety_gate",
        "darkharness_trust_ladder_gate",
        "darkharness_readiness_gap_gate",
        "darkharness_operator_approval",
        "darkharness_rollback_plan",
    ),
    "shared/mesh_runtime/perennial/signing.py": (
        "build_ed25519_signature_proof",
        "verify_ed25519_signature_proof",
        "orbital_mesh_ed25519_v1",
    ),
    "docs/security-audit-readiness.md": (
        "OpenSSF Control Map",
        "Regular Audit Cadence",
        "E2E Audit Commands",
        "Audit Evidence Package",
        "Procurement Security Package",
        "config/procurement-security.package.json",
        "scripts/verify_procurement_security_package.py",
        "OpenSSF Best Practices Badge",
    ),
    "services/control_plane.py": (
        "mesh_brain_artifact_uri_prefix",
        "mesh_brain_artifact_upload_proof_record",
        "mesh_brain_artifact_upload_proof_verified",
        "mesh_brain_serving_base_url",
        "mesh_brain_serving_model",
        "build_production_artifact_ref",
        "production_artifact",
        "release_provenance_complete",
        "release_provenance_path",
        "build_failure_mode_library",
        "build_watcher_ownership",
        "build_approval_queue",
    ),
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify the production cut-list release packet references active orbital-mesh paths.")
    parser.add_argument("--json", action="store_true", help="Emit JSON instead of text.")
    args = parser.parse_args()

    checks: list[dict[str, Any]] = []
    checks.extend(_check_image_defaults())
    checks.extend(_check_required_paths("doc", REQUIRED_DOCS))
    checks.extend(_check_required_paths("test", REQUIRED_TESTS))
    checks.extend(_check_required_paths("script", REQUIRED_SCRIPTS))
    checks.extend(_check_required_paths("config", REQUIRED_CONFIGS))
    checks.extend(_check_api_markers())
    checks.extend(_check_required_markers())
    checks.extend(_check_docs_reference_active_paths())

    failed = [check for check in checks if check["status"] != "pass"]
    payload = {
        "status": "pass" if not failed else "fail",
        "checks": checks,
    }
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        for check in checks:
            print(f"{check['status']}: {check['name']} - {check['detail']}")
    return 0 if not failed else 1


def _check_image_defaults() -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []
    for rel, markers in IMAGE_DEFAULTS.items():
        text = _read(rel)
        missing = [marker for marker in markers if marker not in text]
        legacy = "mesh-intelligence" in text
        status = "pass" if not missing and not legacy else "fail"
        detail = "orbital-mesh image defaults present"
        if missing:
            detail = f"missing defaults: {missing}"
        if legacy:
            detail = "legacy mesh-intelligence image/default reference present"
        checks.append({"name": f"image defaults: {rel}", "status": status, "detail": detail})
    return checks


def _check_required_paths(kind: str, paths: tuple[str, ...]) -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []
    for rel in paths:
        path = REPO_ROOT / rel
        checks.append(
            {
                "name": f"{kind} exists: {rel}",
                "status": "pass" if path.exists() else "fail",
                "detail": "present" if path.exists() else "missing",
            }
        )
    return checks


def _check_api_markers() -> list[dict[str, Any]]:
    text = _read("control_plane_server.py")
    return [
        {
            "name": f"API marker: {marker}",
            "status": "pass" if marker in text else "fail",
            "detail": "present" if marker in text else "missing",
        }
        for marker in REQUIRED_API_MARKERS
    ]


def _check_required_markers() -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []
    for rel, markers in REQUIRED_MARKERS.items():
        text = _read(rel)
        missing = [marker for marker in markers if marker not in text]
        checks.append(
            {
                "name": f"release marker: {rel}",
                "status": "pass" if not missing else "fail",
                "detail": "markers present" if not missing else f"missing markers: {missing}",
            }
        )
    return checks


def _check_docs_reference_active_paths() -> list[dict[str, Any]]:
    references = {
        "docs/evaluation-kits.md": (
            "docker-compose.stack.yml",
            "docker-compose.prod.yml",
            "config/ownership.registry.json",
            "config/policy-lifecycle.manifest.json",
            "docs/deployment-compatibility.md",
            "docs/agentic-operator-core-import-plan.md",
            "scripts/compose_stack_smoke.sh",
            "scripts/prod_smoke.sh",
        ),
        "docs/design-partner-packet.md": (
            "docs/production-hardening-records.md",
            "docs/production-live-runbook.md",
            "docs/production-readiness-validation.md",
            "scripts/verify_design_partner_packet.py",
        ),
        "docs/postgres-restart-proof.md": (
            "scripts/verify_postgres_restart_proof.py",
            "shared/mesh_runtime/postgres_state.py",
        ),
        "docs/release-provenance.md": (
            "scripts/generate_release_provenance.py",
            "scripts/generate_release_image_handoff.py",
            "scripts/verify_release_image_handoff.py",
            "scripts/verify_mesh_brain_artifact_registry.py",
            ".github/workflows/release-image-handoff.yml",
        ),
        "docs/authenticated-ingress.md": (
            "control_plane_server.py",
            "scripts/verify_authenticated_ingress.py",
            "scripts/verify_authenticated_ingress_deployment.py",
        ),
        "docs/reference-architectures.md": (
            "docker-compose.stack.yml",
            "docker-compose.prod.yml",
            "config/ownership.registry.json",
            "config/policy-lifecycle.manifest.json",
            "docs/deployment-compatibility.md",
            "docs/agentic-operator-core-import-plan.md",
            "docs/authenticated-ingress.md",
            "scripts/prod_smoke.sh",
            "scripts/verify_postgres_restart_proof.py",
            "scripts/generate_release_provenance.py",
            "services/ingest/kubernetes_live_signal.py",
            "services/watchers/kubernetes.py",
            "services/actuators/service.py",
            "docker-compose.latentmas.yml",
            "mesh_brain/",
            "fixtures/signals/",
            "policies/",
        ),
        "docs/deployment-compatibility.md": (
            "docker-compose.stack.yml",
            "docker-compose.prod.yml",
            "docs/authenticated-ingress.md",
            "docs/agentic-operator-core-import-plan.md",
            "scripts/prod_smoke.sh",
        ),
        "docs/agentic-operator-core-import-plan.md": (
            "config/agentic-operator-source.provenance.json",
            "scripts/verify_agentic_operator_source_provenance.py",
        ),
        "docs/pilot-slo-error-budget.md": (
            "docs/design-partner-packet.md",
            "scripts/prod_smoke.sh",
            "scripts/verify_authenticated_ingress.py",
            "scripts/verify_postgres_restart_proof.py",
            "scripts/generate_release_provenance.py",
            "scripts/verify_mesh_brain_artifact_registry.py",
        ),
        "docs/post-training/runtime.md": (
            "mesh_brain/artifact_registry.py",
            "scripts/verify_mesh_brain_artifact_registry.py",
        ),
        "docs/security-audit-readiness.md": (
            "SECURITY.md",
            ".github/workflows/security.yml",
            ".github/dependabot.yml",
            ".github/CODEOWNERS",
            "scripts/verify_security_audit_readiness.py",
            "scripts/generate_release_provenance.py",
            "scripts/verify_release_cut_list.py",
        ),
    }
    checks: list[dict[str, Any]] = []
    for doc, expected in references.items():
        text = _read(doc)
        missing = [rel for rel in expected if rel not in text or not (REPO_ROOT / rel).exists()]
        checks.append(
            {
                "name": f"active path references: {doc}",
                "status": "pass" if not missing else "fail",
                "detail": "all references present" if not missing else f"missing references: {missing}",
            }
        )
    return checks


def _read(rel: str) -> str:
    return (REPO_ROOT / rel).read_text(encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
