// <generated-control-plane-contracts>
/* eslint-disable */
// Generated by scripts/generate_control_plane_contracts.py. Do not edit this block manually.
export type JsonObject = Record<string, unknown>;

export interface GoalRecord {
  goal_id: string;
  title: string;
  objective: string;
  success_criteria: string[];
  status: string;
  created_at: string;
  updated_at: string;
  tags: string[];
  note_path?: string | null;
}

export interface RunEvent {
  event_id: string;
  run_id: string;
  sequence: number;
  stage: string;
  event_type: string;
  recorded_at: string;
  payload: Record<string, any>;
  summary?: Record<string, any> | null;
  merkle_leaf_hash?: string | null;
  artifact_key?: string | null;
  integration_name?: string | null;
  status?: string | null;
}

export interface RunSession {
  run_id: string;
  created_at: string;
  updated_at: string;
  goal_id: string | null;
  scenario_key: string | null;
  stage: string;
  status: string;
  steering_mode: string;
  auto_mode: boolean;
  pause_points: string[];
  pending_pause_stage: string | null;
  evaluation_mode: string;
  orchestration_mode: string;
  latest_event_id: string | null;
  latest_event_sequence: number;
  latest_merkle_root: string | null;
  operator_notes: string[];
  artifacts: Record<string, any>;
  error?: string | null;
}

export interface SteeringCommand {
  command_id: string;
  run_id: string;
  command_type: string;
  issued_at: string;
  payload: Record<string, any>;
}

export interface AgentAttempt {
  attempt_id: string;
  task_id: string;
  run_id: string;
  agent: string;
  adapter: string;
  status: string;
  started_at: string;
  completed_at: string;
  summary: string;
  changed_files: string[];
  test_results: Record<string, any>[];
  risk_flags: string[];
  recommended_action: string;
  output: Record<string, any>;
  observations_proposed: Record<string, any>[];
  claims_proposed: Record<string, any>[];
  procedures_proposed: Record<string, any>[];
  citations: Record<string, any>[];
  contradictions_detected: Record<string, any>[];
  memory_actions_requested: string[];
}

export interface AgentTask {
  task_id: string;
  run_id: string;
  kind: string;
  status: string;
  created_at: string;
  updated_at: string;
  allowed_paths: string[];
  test_commands: string[];
  kubernetes_scope: Record<string, any>;
  memory_scope: Record<string, any>;
  memory_packet: Record<string, any>;
  memory_write_policy: Record<string, any>;
  open_questions: string[];
  agents: string[];
  orchestration_topology: Record<string, any>;
  lane_routing: Record<string, any>;
  attempts: AgentAttempt[];
  selected_attempt_id?: string | null;
}

export interface IntegrationStatus {
  name: string;
  ready: boolean;
  detail: string;
  command?: string | null;
  url?: string | null;
  primary_route?: string | null;
  fallback_route?: string | null;
  warnings: string[];
  certification: string;
  required_before: string;
  posture: string;
}

export interface IntegrationReadiness {
  checked_at: string;
  profile: string;
  status: string;
  required_checks: Record<string, any>;
  optional_checks: Record<string, any>;
  blockers: string[];
  blocker_details: Record<string, any>;
  connector_certification: Record<string, any>;
  orchestration_topology: Record<string, any>;
  promptfoo: IntegrationStatus;
  hermes: IntegrationStatus;
  goose: IntegrationStatus;
  latentmas: IntegrationStatus;
  deepagents: IntegrationStatus;
  zaxy: IntegrationStatus;
  eventloom: IntegrationStatus;
  neo4j_projection: IntegrationStatus;
  zaxy_mcp: IntegrationStatus;
  langgraph_checkpointing: IntegrationStatus;
  vault_path: string;
  state_path: string;
  integrations_config_path: string;
}

export interface MerkleProofStep {
  position: string;
  hash: string;
}

export interface MerkleSnapshot {
  run_id: string;
  root_hash: string;
  leaf_count: number;
  event_ids: string[];
}

export interface MerkleProof {
  run_id: string;
  event_id: string;
  leaf_hash: string;
  root_hash: string;
  proof: MerkleProofStep[];
  valid: boolean;
}

export type RunSessionRecord = RunSession;
export type RunEventRecord = RunEvent;

export interface RunDetail extends RunSession {
  events: RunEvent[];
  merkle: MerkleSnapshot;
}

export interface SystemSnapshot {
  timestamp: string;
  runs: RunSessionRecord[];
  readiness: IntegrationReadiness;
  active_runs: RunSessionRecord[];
}
// </generated-control-plane-contracts>

export interface ConnectorCredentialBoundary {
  service_account_ref?: string | null;
  credential_mode?: string | null;
  production_actuator_credentials_allowed?: boolean | null;
  repo_write_credentials_allowed?: boolean | null;
  runtime_secret_mount_required?: boolean | null;
  rotation_evidence_ref?: string | null;
  break_glass_recording_required?: boolean | null;
}

export interface ConnectorCertificationRecord {
  connector_id: string;
  display_name?: string | null;
  domain?: string | null;
  state?: string | null;
  certified_state?: string | null;
  observed_state?: string | null;
  required_before?: string | null;
  authority_posture?: string | null;
  credential_policy?: string | null;
  credential_boundary?: ConnectorCredentialBoundary | null;
  degraded_behavior?: string | null;
  allowed_scopes?: string[] | null;
  evidence_refs?: string[] | null;
  blockers?: string[] | null;
  detail?: string | null;
}

export interface ConnectorCertificationPacket {
  schema_version: string;
  generated_at: string;
  status: string;
  registry_path?: string | null;
  registry_sha256?: string | null;
  blockers: string[];
  connectors: Record<string, ConnectorCertificationRecord>;
}

export type DeliveryContextNodeKind =
  | "pull_request"
  | "commit"
  | "ci"
  | "build"
  | "deploy"
  | "runtime"
  | "policy"
  | "agent"
  | "feedback"
  | "evidence_gap"
  | "zaxy_mirror"
  | "langgraph_workflow"
  | "agent_attempt";

export type DeliveryContextStage =
  | "pr"
  | "ci"
  | "build"
  | "deploy"
  | "runtime"
  | "policy"
  | "agent"
  | "feedback"
  | "evidence"
  | "zaxy"
  | "langgraph";

export type DeliveryContextStatus =
  | "passed"
  | "failed"
  | "blocked"
  | "missing"
  | "running"
  | "pending"
  | "mirrored"
  | "degraded"
  | "unknown";

export interface DeliveryContextRef {
  label: string;
  value: string;
  url?: string | null;
}

export interface DeliveryContextNode {
  id: string;
  kind: DeliveryContextNodeKind;
  stage: DeliveryContextStage;
  title: string;
  status: DeliveryContextStatus;
  summary?: string | null;
  occurred_at?: string | null;
  refs?: DeliveryContextRef[] | null;
  metadata?: Record<string, unknown> | null;
}

export interface DeliveryContextEdge {
  id: string;
  source: string;
  target: string;
  relation: string;
  status?: DeliveryContextStatus | null;
  evidence_ref?: string | null;
}

export interface DeliveryEvidenceGap {
  id: string;
  title: string;
  severity: "info" | "warn" | "blocker";
  summary: string;
  missing_ref?: string | null;
  owner?: string | null;
}

export interface ZaxyMirrorStatus {
  enabled: boolean;
  status: "mirrored" | "pending" | "degraded" | "unavailable";
  latest_sequence?: number | null;
  latest_event_id?: string | null;
  merkle_root?: string | null;
  projection_lag_ms?: number | null;
  graph_available?: boolean | null;
  redaction_status?: string | null;
}

export interface LangGraphWorkflowRef {
  workflow_id: string;
  thread_id?: string | null;
  status: string;
  evidence_packet_id?: string | null;
  zaxy_checkout_ref?: string | null;
  agent_attempt_ids?: string[] | null;
}

export interface DeliveryContextGraph {
  schema_version: string;
  run_id: string;
  service?: string | null;
  repository?: string | null;
  generated_at: string;
  summary?: string | null;
  nodes: DeliveryContextNode[];
  edges: DeliveryContextEdge[];
  evidence_gaps: DeliveryEvidenceGap[];
  zaxy_mirror?: ZaxyMirrorStatus | null;
  langgraph_workflows?: LangGraphWorkflowRef[] | null;
  agent_attempt_refs?: string[] | null;
}

export interface ApprovalQueueItem {
  queue_id: string;
  run_id: string;
  created_at: string;
  updated_at: string;
  scenario_key?: string | null;
  service?: string | null;
  namespace?: string | null;
  environment: string;
  stage: string;
  pending_pause_stage?: string | null;
  steering_mode: string;
  decision_type?: string | null;
  risk_level?: string | null;
  final_recommendation?: string | null;
  approval_state: "pending" | "blocked";
  blockers: string[];
  requested_by?: Record<string, any> | null;
  owner?: Record<string, any> | null;
  approver_roles: string[];
  allowed_commands: string[];
  evidence_refs: string[];
  latest_event_id?: string | null;
}

export interface ApprovalQueuePacket {
  schema_version: string;
  generated_at: string;
  status: "empty" | "ready" | "blocked";
  pending_count: number;
  blocked_count: number;
  source_refs: string[];
  items: ApprovalQueueItem[];
}

export interface HealthSnapshot {
  status: string;
  timestamp: string;
  environment: string;
  version: string;
  commit: string;
}

export type ConnectionStatus = "connected" | "reconnecting" | "disconnected";
export type InspectorTab =
  | "overview"
  | "evidence"
  | "policy"
  | "execution"
  | "feedback"
  | "agents"
  | "vault"
  | "merkle"
  | "code"
  | "research";

export interface ScenarioRecord {
  key: string;
  title: string;
  file: string;
  summary: {
    service: string;
    endpoint: string;
    flag_key: string;
    latency_delta_ms: number;
  };
}

export interface SimulationScenarioRecord {
  scenario_id: string;
  title: string;
  signal_payload: Record<string, any>;
  expected_decision_type?: string | null;
  expected_outcome?: string | null;
  fault_type: string;
  sandbox: Record<string, any>;
  tags: string[];
  standards_refs: string[];
}

export interface BenchmarkRecord {
  benchmark_id: string;
  run_id: string;
  scenario_id: string;
  recorded_at: string;
  score: number;
  passed: boolean;
  dimensions: Record<string, any>;
  dataset_ref?: string | null;
}

export interface PolicySimulationResult {
  mutates: boolean;
  source: Record<string, any>;
  triggered: boolean;
  trigger?: Record<string, any> | null;
  evidence_pack?: Record<string, any> | null;
  scenario_analysis?: Record<string, any> | null;
  decision?: Record<string, any> | null;
  evaluation?: Record<string, any> | null;
  blockers: string[];
  allowed_action?: Record<string, any> | null;
  denied_action?: Record<string, any> | null;
  rollback_path?: string | null;
}

export interface KillSwitchStatus {
  watchers: WatcherStatus;
  live_execution_enabled: boolean;
  force_approval_gate: boolean;
  allowed_contexts: string[];
  allowed_namespaces: string[];
  actions?: string[];
  operator?: Record<string, any> | null;
}

export interface PilotGoNoGoPacket {
  packet_version: string;
  generated_at: string;
  status: string;
  checks: Record<string, boolean>;
  missing_evidence: string[];
  readiness: IntegrationReadiness;
  release_provenance?: Record<string, any>;
  on_call_drill?: Record<string, any>;
  mesh_brain_artifact_upload_proof?: Record<string, any>;
  observed: {
    run_count: number;
    approved_run_ids: string[];
    live_action_run_ids: string[];
    denied_action_run_ids: string[];
    merkle_run_ids: string[];
    mesh_brain_model_kernel_run_ids?: string[];
    mesh_brain_live_canary_smoke_run_ids?: string[];
    mesh_brain_canary_lanes?: { tenant_id: string; task_type: string }[];
    mesh_brain_rollback_drill_run_ids?: string[];
  };
}

export interface RunExportPackage {
  package_version: string;
  export_id: string;
  generated_at: string;
  run_id: string;
  path: string;
  package_sha256: string;
  session: RunSessionRecord;
  timeline_json: RunEventRecord[];
  postmortem_markdown: string;
  evidence_artifacts: Record<string, any>;
  decision_record?: Record<string, any> | null;
  evaluation_record?: Record<string, any> | null;
  execution_record?: Record<string, any> | null;
  feedback_record?: Record<string, any> | null;
  approval_records: Array<Record<string, any>>;
  operator_notes: string[];
  merkle: {
    snapshot: MerkleSnapshot;
    latest_event_proof?: MerkleProof | null;
  };
  vault_documents: Array<{ path: string; content: string }>;
  checks: Record<string, boolean>;
  redaction: {
    enabled: boolean;
    secret_markers: string[];
    replacement: string;
  };
  retention: {
    retention_days: number;
    delete_after: string;
    reviewed: boolean;
    review_required_before: string;
    delete_command: string;
  };
  size_control: {
    max_bytes: number;
    initial_bytes: number;
    final_bytes: number;
    truncated: boolean;
    omitted_fields: string[];
  };
}

export interface DarkharnessPilotPacket {
  packet: "darkharness.pilot_packet.v1";
  status?: "blocked" | string;
  run_id?: string;
  packet_id?: string;
  generated_at?: string;
  customer_boundary?: string;
  pilot_scope_id?: string;
  missing_evidence?: string[];
  checks?: Record<string, boolean>;
  implemented_evidence?: {
    readiness?: Record<string, any>;
    go_no_go?: Record<string, any>;
    run_exports?: Array<Record<string, any>>;
    merkle_proofs?: Array<Record<string, any>>;
    denied_action_proofs?: Array<Record<string, any>>;
    allowed_action_proofs?: Array<Record<string, any>>;
    postgres_restart_proof?: Record<string, any> | null;
  };
  perennial_records?: {
    sensitive_reservoirs?: Array<Record<string, any>>;
    agent_action_records?: Array<Record<string, any>>;
    epistemic_states?: Array<Record<string, any>>;
    ontological_states?: Array<Record<string, any>>;
    governance_commits?: Array<Record<string, any>>;
    proof_envelopes?: Array<Record<string, any>>;
  };
  boundaries: {
    raw_reservoir_egress: string;
    external_model_calls: string;
    production_actions_approval_required: boolean;
  };
  claim_boundary: {
    implemented: string[];
    proposed: string[];
    not_implemented: string[];
  };
}

export interface TrustLadderEntry {
  action_class: string;
  service: string;
  level: string;
  previous_level: string;
  total_runs: number;
  successful_runs: number;
  success_rate: number;
  consecutive_failures: number;
  promotion_count: number;
  demotion_count: number;
  override_count: number;
  last_outcome?: string | null;
  last_outcome_at?: string | null;
  last_level_change_at?: string | null;
  last_override_at?: string | null;
  manual_override_reason?: string | null;
  next_level?: string | null;
  autonomy_ceiling_reason?: string | null;
  promotion_blockers?: string[];
  promotion_requirements?: {
    min_runs?: number;
    min_success_rate?: number;
  };
}

export interface ServiceAgentRecord {
  service: string;
  scope: Record<string, string[]>;
  runbook_path?: string | null;
  preferred_lanes: string[];
  autonomy_overrides: Record<string, string>;
}

export interface ResearchSessionRecord {
  session_id: string;
  directory: string;
  question: string;
  status: string;
  minimax_model?: string | null;
  minimax_route?: string | null;
  goose?: Record<string, unknown> | null;
  updated_at: string;
  has_final_report: boolean;
  research_intelligence?: ResearchIntelligence;
}

export interface ResearchSessionDetail {
  session_id: string;
  directory: string;
  manifest: Record<string, unknown>;
  final_report_markdown: string | null;
  final_report_relative: string | null;
  research_intelligence?: ResearchIntelligence;
}

export interface ResearchAnchor {
  key: string;
  label: string;
  terms: string[];
  score: number;
}

export interface ResearchIntelligence {
  classification: "repo_grounded" | "mixed" | "off_domain" | "needs_review";
  repo_grounding_score: number;
  off_domain_score: number;
  flags: string[];
  anchors: ResearchAnchor[];
  repo_terms?: string[];
  off_domain_terms?: string[];
  unsupported_claim_terms?: string[];
  evidence_limit_terms?: string[];
  extracted_claims?: string[];
  extracted_risks?: string[];
  extracted_actions?: string[];
  documents_read?: string[];
  redacted_reasoning_blocks?: number;
}

export interface ResearchCorpusIntelligence {
  sessions_analyzed: number;
  classification_counts: Record<string, number>;
  recurring_flags: Record<string, number>;
  accepted_anchors: Array<{ key: string; label: string; session_count: number }>;
  drift_sessions: Array<{ session_id: string; directory: string; off_domain_terms: string[] }>;
  next_actions: string[];
}

export type LabyrinthSeverity = "info" | "warning" | "danger" | "success";
export type LabyrinthThread = "main" | "evidence" | "threshold" | "execution" | "memory" | "watcher";

export interface LabyrinthJourney {
  id: string;
  kind: "run" | "research" | "watcher";
  source: string;
  title: string;
  status: string;
  summary: string;
  updated_at: string;
  event_count: number;
  risk_level?: string | null;
  selected?: boolean;
}

export interface LabyrinthCrossing {
  id: string;
  journey_id: string;
  type: string;
  label: string;
  status: string;
  thread: LabyrinthThread;
  sequence: number;
  recorded_at?: string | null;
  duration_ms?: number | null;
  actor?: string | null;
  target?: string | null;
  preview_in?: string | null;
  preview_out?: string | null;
  event_id?: string | null;
  artifact_key?: string | null;
  evidence_refs: string[];
  severity: LabyrinthSeverity;
}

export interface LabyrinthGuidepost {
  id: string;
  journey_id: string;
  severity: LabyrinthSeverity;
  title: string;
  detail: string;
  evidence_refs: string[];
}

export interface EvidenceGraphNode {
  id: string;
  type: string;
  label?: string | null;
  analyzer?: string | null;
  confidence?: number | null;
  requires_review?: boolean | null;
  merkle_root?: string | null;
}

export interface EvidenceGraphEdge {
  source: string;
  target: string;
  kind?: string | null;
}

export interface EvidenceGraph {
  nodes: EvidenceGraphNode[];
  edges: EvidenceGraphEdge[];
  merkle_root?: string | null;
}

export interface ScenarioAnalysis {
  analysis_id: string;
  trigger_id: string;
  created_at: string;
  suggested_decision_type: string;
  confidence: number;
  risk_level: string;
  autonomy_tier_hint: string;
  required_review_reasons: string[];
  evidence_refs: string[];
  evidence_nodes: Array<Record<string, any>>;
  subdecisions: Array<Record<string, any>>;
  merkle_root?: string | null;
  merkle_event_ids?: string[];
}

export interface WatcherStatus {
  watchers: Array<{
    name: string;
    signal_source: string;
    interval_seconds: number;
    running: boolean;
    detail?: Record<string, any>;
    ownership?: {
      owner?: {
        owner_id?: string;
        display_name?: string;
        source_refs?: string[];
      };
      blockers?: string[];
      resolved_target_count?: number;
      target_count?: number;
      targets?: Array<Record<string, any>>;
    } | null;
  }>;
  ownership?: Record<string, any>;
}

export interface VaultTreeEntry {
  path: string;
  name: string;
  type: "file" | "directory";
  children?: VaultTreeEntry[];
}

export interface ToastMessage {
  id: string;
  variant: "success" | "error" | "info" | "warning";
  title: string;
  description?: string;
  duration?: number;
}
